import PageShell from '../../_components/PageShell';
import SourceList from '../../_components/SourceList';
import { BreadcrumbSchema } from '../../schema';
import { pageMetadata } from '@/lib/seo';
import { officialSources } from '@/lib/site';
const path='/world-cup-2026/host-cities';
export const metadata=pageMetadata({title:'World Cup 2026 Host Cities — Canada, Mexico & USA',description:'Explore the 16 host cities that staged World Cup 2026 matches across Canada, Mexico, and the United States.',path});
const countries=[{name:'Canada',cities:['Toronto','Vancouver']},{name:'Mexico',cities:['Guadalajara','Mexico City','Monterrey']},{name:'United States',cities:['Atlanta','Boston','Dallas','Houston','Kansas City','Los Angeles','Miami','New York New Jersey','Philadelphia','San Francisco Bay Area','Seattle']}];
export default function Page(){return <><BreadcrumbSchema items={[{name:'Home',path:'/'},{name:'World Cup 2026',path:'/world-cup-2026'},{name:'Host cities',path}]}/><PageShell eyebrow="Sixteen host cities · Three countries" title="The North American cities that hosted World Cup 2026." description="Canada, Mexico, and the United States jointly staged the tournament. Mexico City hosted the opening match, while New York New Jersey hosted the final." breadcrumbs={[{label:'Home',href:'/'},{label:'2026 Archive',href:'/world-cup-2026'},{label:'Host cities'}]}><div className="grid gap-5 lg:grid-cols-3">{countries.map(c=><section key={c.name} className="glass rounded-2xl p-7"><p className="eyebrow">{c.cities.length} host {c.cities.length===1?'city':'cities'}</p><h2 className="mt-3 text-3xl font-black">{c.name}</h2><ul className="mt-6 grid gap-3 text-sm text-slate-300">{c.cities.map(city=><li key={city} className="rounded-xl border border-white/5 bg-white/[.025] px-4 py-3 font-bold">{city}</li>)}</ul></section>)}</div><section className="mt-14 rounded-2xl border border-white/10 bg-white/[.035] p-7 md:p-10"><h2 className="text-3xl font-black">A host-city page needs more than a city name.</h2><p className="mt-4 max-w-4xl text-sm leading-7 text-slate-400">This rebuild does not create sixteen doorway pages. A future city page must contain verified venue details, match history, transport/accessibility information, original photography or data, and primary sources before it becomes indexable.</p></section><SourceList sources={[{name:'FIFA host-city announcement',url:officialSources.fifaHosts},{name:'FIFA tournament hub',url:officialSources.fifaTournament}]}/></PageShell></>}
