export interface BestCategory {
  slug: string
  title: string
  metaTitle: string
  metaDescription: string
  primaryKeyword: string
  description: string
  tools: {
    rank: number
    name: string
    path: string
    tagline: string
    pros: string[]
    free: boolean
    accountRequired: boolean
  }[]
}

export const BEST_CATEGORIES: BestCategory[] = [
  {
    slug: "ai-text-detectors",
    title: "Best Free AI Text Detectors",
    metaTitle: "Best Free AI Text Detectors in 2026 — Ranked & Compared",
    metaDescription: "The best free AI text detectors compared: accuracy, free limits, no-account access, and support for ChatGPT, Claude, and Gemini detection.",
    primaryKeyword: "best ai text detectors",
    description: "Compare the top free AI text detectors by accuracy, feature depth, and ease of use. All tools tested against ChatGPT, Claude, and Gemini output.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — AI Text Detector",
        path: "/tools/detect-text-ai",
        tagline: "Multi-model detection with no account required",
        pros: ["No account or signup", "Multi-model cross-validation", "Built-in humanizer", "Unlimited free use"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "GPTZero",
        path: "https://gptzero.me",
        tagline: "Academic-focused AI detector with detailed scoring",
        pros: ["High accuracy", "Sentence-level highlighting", "Educator-trusted"],
        free: false,
        accountRequired: true,
      },
      {
        rank: 3,
        name: "ZeroGPT",
        path: "https://zerogpt.com",
        tagline: "Fast single-score AI detection, no account needed",
        pros: ["No account required", "Fast results", "Supports long text"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "Originality.ai",
        path: "https://originality.ai",
        tagline: "AI detection + plagiarism check for content teams",
        pros: ["Combines AI detection and plagiarism", "Team features", "API access"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "ai-image-generators",
    title: "Best Free AI Image Generators",
    metaTitle: "Best Free AI Image Generators in 2026 — No Account Needed",
    metaDescription: "The best free AI image generators compared: no signup options, image quality, resolution limits, and speed.",
    primaryKeyword: "best free ai image generators",
    description: "The top free AI image generators ranked by image quality, generation speed, and how much you can create without paying.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — AI Image Generator",
        path: "/tools/free-ai-image-generator",
        tagline: "Free AI image generation — no account, no limits",
        pros: ["No account required", "Flux model output", "Instant generation", "Multiple aspect ratios"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "Midjourney",
        path: "https://midjourney.com",
        tagline: "The gold standard for artistic AI image generation",
        pros: ["Best artistic quality", "Active community", "Regular model updates"],
        free: false,
        accountRequired: true,
      },
      {
        rank: 3,
        name: "Adobe Firefly",
        path: "https://firefly.adobe.com",
        tagline: "Copyright-safe AI images with commercial license",
        pros: ["Commercially safe", "Style reference", "Adobe integration"],
        free: false,
        accountRequired: true,
      },
      {
        rank: 4,
        name: "Leonardo.ai",
        path: "https://leonardo.ai",
        tagline: "Generous free tier with high-quality models",
        pros: ["150 tokens/day free", "Multiple model styles", "ControlNet support"],
        free: true,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "ai-paraphrasing-tools",
    title: "Best Free AI Paraphrasing Tools",
    metaTitle: "Best Free AI Paraphrasing Tools in 2026 — No Signup",
    metaDescription: "The best free AI paraphrasing and rewriting tools compared. Ranked by output quality, free limits, tone options, and whether they require an account.",
    primaryKeyword: "best ai paraphrasing tools free",
    description: "Compare the top free AI paraphrasing tools. Find the best option for rewriting essays, marketing copy, and AI-generated content.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — AI Paraphrasing Tool",
        path: "/tools/ai-paraphrasing-tool-and-rewriter",
        tagline: "Free AI paraphraser with tone selection, no account",
        pros: ["No account required", "Multiple tone options", "Preserves meaning", "Instant rewriting"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "QuillBot",
        path: "https://quillbot.com",
        tagline: "Industry-standard paraphraser with 7 writing modes",
        pros: ["7 modes", "Grammar check included", "Word flipper"],
        free: false,
        accountRequired: true,
      },
      {
        rank: 3,
        name: "Wordtune",
        path: "https://wordtune.com",
        tagline: "AI rewriter focused on sentence-level suggestions",
        pros: ["Inline suggestions", "Shorten/expand modes", "Chrome extension"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "ai-humanizers",
    title: "Best Free AI Text Humanizers",
    metaTitle: "Best Free AI Text Humanizers in 2026 — Bypass AI Detectors",
    metaDescription: "The best free AI humanizer tools compared. Find the best option for making ChatGPT and Claude text sound natural and bypass AI detection.",
    primaryKeyword: "best ai humanizers free",
    description: "Compare the top free AI text humanizers. Tested for ability to bypass GPTZero, Turnitin, and Originality.ai.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — AI Text Humanizer",
        path: "/tools/clean-text-using-ai",
        tagline: "Free humanizer that bypasses GPTZero and Turnitin",
        pros: ["No account required", "Preserves original meaning", "Multi-model rewriting", "Instant results"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "Undetectable.ai",
        path: "https://undetectable.ai",
        tagline: "Specialized humanizer built to evade AI detectors",
        pros: ["Tested against 9 detectors", "Readability modes", "API access"],
        free: false,
        accountRequired: true,
      },
      {
        rank: 3,
        name: "HIX Bypass",
        path: "https://hix.ai/bypass-ai-detection",
        tagline: "AI humanizer from HIX.ai writing suite",
        pros: ["Multiple humanization modes", "Integrated with HIX editor", "Fast output"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "code-tools",
    title: "Best Free Online Code Tools",
    metaTitle: "Best Free Online Code Tools in 2026 — No Signup Needed",
    metaDescription: "The best free online coding tools compared: code explainers, error solvers, converters, and formatters. All browser-based, no download needed.",
    primaryKeyword: "best free coding tools online",
    description: "The top free browser-based coding tools for developers. Explain, debug, convert, and format code instantly with no account required.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — Code Explainer",
        path: "/tools/code-explainer",
        tagline: "Explain any code in plain English — 20+ languages",
        pros: ["No account required", "20+ languages", "3 explanation levels", "Beginner to expert"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "TheFreeAITools — Error Message Solver",
        path: "/tools/error-message-solver",
        tagline: "Paste any error, get root cause + fix instantly",
        pros: ["Stack trace analysis", "22 frameworks", "Step-by-step fix", "Code fix included"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "TheFreeAITools — Code Converter",
        path: "/tools/code-converter",
        tagline: "Convert code between 15+ programming languages",
        pros: ["15+ languages", "SQL dialect support", "Idiomatic output", "Quick-select pairs"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "GitHub Copilot",
        path: "https://github.com/features/copilot",
        tagline: "AI pair programmer for IDE integration",
        pros: ["IDE integration", "Real-time suggestions", "Best-in-class code completion"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "url-shorteners",
    title: "Best Free URL Shorteners",
    metaTitle: "Best Free URL Shorteners in 2026 — No Account, No Expiration",
    metaDescription: "The best free URL shorteners compared: no-account options, link expiration, QR code generation, and analytics features.",
    primaryKeyword: "best free url shorteners",
    description: "Compare the top free URL shorteners by features, limits, and whether you need an account to create short links.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — URL Shortener",
        path: "/tools/url-shortener",
        tagline: "Free URL shortener with QR codes — no account, no expiration",
        pros: ["No account required", "Free QR code generation", "Links never expire", "Instant shortening"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "TinyURL",
        path: "https://tinyurl.com",
        tagline: "Simple free URL shortening with custom aliases",
        pros: ["Custom aliases", "No account needed", "Simple interface"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "Bitly",
        path: "https://bit.ly",
        tagline: "Professional URL shortener with click analytics",
        pros: ["Click analytics", "Branded links", "QR codes (paid)", "Bulk shortening"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "ai-writing-tools",
    title: "Best Free AI Writing Tools",
    metaTitle: "Best Free AI Writing Tools in 2026 — No Account Needed",
    metaDescription: "The best free AI writing tools compared: story generators, prompt generators, paraphrasers, and content writers. All tested for output quality.",
    primaryKeyword: "best free ai writing tools",
    description: "Compare the top free AI writing tools for content creators, students, and marketers. All rated for output quality and free access.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — AI Story Generator",
        path: "/tools/ai-story-and-novel-generator",
        tagline: "Free AI story and novel generator — any genre",
        pros: ["No account required", "Multiple genres", "Long-form output", "Character development"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "TheFreeAITools — AI Prompt Generator",
        path: "/tools/ai-prompt-generator",
        tagline: "Generate optimized prompts for any AI tool",
        pros: ["No account required", "Multiple output formats", "Detailed prompts", "Free forever"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "TheFreeAITools — AI Paraphrasing Tool",
        path: "/tools/ai-paraphrasing-tool-and-rewriter",
        tagline: "Rewrite any text with AI in multiple tones",
        pros: ["No account required", "Tone selection", "Meaning preservation", "Instant results"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "Copy.ai",
        path: "https://copy.ai",
        tagline: "AI copywriting tool with 90+ content templates",
        pros: ["90+ templates", "Brand voice", "Team collaboration"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "image-compressors",
    title: "Best Free Image Compressors Online",
    metaTitle: "Best Free Image Compressors Online in 2026 — No Account Needed",
    metaDescription: "The best free image compressors compared: file size reduction, supported formats, privacy (local vs server), and whether an account is required.",
    primaryKeyword: "best free image compressor online",
    description: "Compare the top free image compressors by compression quality, supported formats, file size limits, and whether your images are uploaded to external servers.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — Image Compressor",
        path: "/tools/image-compressor",
        tagline: "Compress JPEG, PNG, WebP in browser — no upload, no account",
        pros: ["No account required", "Files never uploaded", "Manual quality slider", "No file limit"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "TinyPNG",
        path: "https://tinypng.com",
        tagline: "Excellent automatic compression for PNG and JPEG",
        pros: ["Best PNG compression algorithm", "Fast", "API available"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "Squoosh",
        path: "https://squoosh.app",
        tagline: "Google's browser-based image compressor with codec control",
        pros: ["Advanced codec options", "Side-by-side comparison", "No upload", "WebP, AVIF support"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "Compressor.io",
        path: "https://compressor.io",
        tagline: "Clean interface for lossy and lossless compression",
        pros: ["Lossy and lossless modes", "Drag and drop", "WebP support"],
        free: true,
        accountRequired: false,
      },
    ],
  },
  {
    slug: "pdf-tools",
    title: "Best Free Online PDF Tools",
    metaTitle: "Best Free Online PDF Tools in 2026 — No Account, No Watermarks",
    metaDescription: "The best free PDF tools online compared: PDF to Word, PDF compression, and editing — rated for free limits, privacy, and ease of use.",
    primaryKeyword: "best free pdf tools online",
    description: "Compare the top free PDF tools by feature depth, free tier limits, and whether your files are uploaded to external servers.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — PDF to Word",
        path: "/tools/pdf-to-word",
        tagline: "Convert PDF to Word free — no account, no server upload",
        pros: ["No account required", "Browser-based processing", "Preserves formatting", "Free forever"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "iLovePDF",
        path: "https://ilovepdf.com",
        tagline: "25+ PDF tools with generous free tier",
        pros: ["25+ tools", "Generous free limits", "No account for basic use", "Mobile app"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "PDF24",
        path: "https://pdf24.org",
        tagline: "Free PDF toolkit with desktop app option",
        pros: ["Desktop app available", "No file upload needed", "25+ tools", "Completely free"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "Smallpdf",
        path: "https://smallpdf.com",
        tagline: "Polished PDF suite with excellent UI",
        pros: ["Best UI", "Mobile apps", "eSign support", "21 tools"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "background-removers",
    title: "Best Free Background Remover Tools",
    metaTitle: "Best Free Background Remover Tools in 2026 — No Account",
    metaDescription: "The best free AI background removers compared: accuracy on hair and complex edges, download resolution, credit limits, and privacy.",
    primaryKeyword: "best free background remover",
    description: "Compare the top free background removal tools by AI accuracy, free download resolution, credit limits, and whether your images are uploaded to servers.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — Background Remover",
        path: "/tools/remove-bg",
        tagline: "Remove backgrounds free — no upload, no account, no credits",
        pros: ["No account required", "Files never uploaded", "No credit system", "Full resolution free"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "Remove.bg",
        path: "https://remove.bg",
        tagline: "Industry-leading AI for complex subjects and hair",
        pros: ["Best accuracy for hair/fur", "API available", "Fast processing", "Bulk download"],
        free: false,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "Canva Background Remover",
        path: "https://canva.com",
        tagline: "Integrated background removal in a full design tool",
        pros: ["Integrated with Canva editor", "Good accuracy", "Immediate use in designs"],
        free: false,
        accountRequired: true,
      },
      {
        rank: 4,
        name: "Erase.bg",
        path: "https://erase.bg",
        tagline: "Free background removal with HD downloads",
        pros: ["HD downloads free", "No account for basic use", "Fast"],
        free: true,
        accountRequired: false,
      },
    ],
  },
  {
    slug: "qr-code-generators",
    title: "Best Free QR Code Generators",
    metaTitle: "Best Free QR Code Generators in 2026 — No Account, No Expiry",
    metaDescription: "The best free QR code generators compared: no-expiry codes, customization options, file format export, and whether an account is required.",
    primaryKeyword: "best free qr code generator",
    description: "Compare the top free QR code generators by customization options, export formats, code permanence, and account requirements.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — QR Code Generator",
        path: "/tools/qr-code-generator",
        tagline: "Free QR codes that never expire — no account required",
        pros: ["No account required", "QR codes never expire", "PNG and SVG export", "Custom error correction"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "QR Code Generator (qr-code-generator.com)",
        path: "https://qr-code-generator.com",
        tagline: "Feature-rich generator with logo support and analytics",
        pros: ["Logo in QR code", "Color customization", "Analytics (paid)", "Dynamic codes (paid)"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "QRCode Monkey",
        path: "https://qrcode-monkey.com",
        tagline: "High-quality QR codes with extensive design options",
        pros: ["High resolution output", "Logo support", "Color gradients", "SVG export"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "Bitly QR Codes",
        path: "https://bitly.com",
        tagline: "QR codes with click tracking and branded links",
        pros: ["Click analytics", "Branded short links", "Dynamic codes", "Bulk creation"],
        free: false,
        accountRequired: true,
      },
    ],
  },
  {
    slug: "password-generators",
    title: "Best Free Password Generators Online",
    metaTitle: "Best Free Password Generators Online in 2026 — Secure, No Account",
    metaDescription: "The best free password generators compared: randomness quality, customization options, passphrase support, and privacy (client-side vs server).",
    primaryKeyword: "best free password generator online",
    description: "Compare the top free password generators by security, customization, passphrase support, and whether password generation happens locally in your browser.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — Password Generator",
        path: "/tools/password-generator",
        tagline: "Cryptographically secure passwords — generated locally, never sent",
        pros: ["No account required", "Cryptographically random", "Passphrase support", "Never sent to servers"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "Bitwarden Password Generator",
        path: "https://bitwarden.com/password-generator",
        tagline: "Open-source password generator from trusted password manager",
        pros: ["Open-source and audited", "Passphrase option", "Part of Bitwarden ecosystem"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "1Password Generator",
        path: "https://1password.com/password-generator",
        tagline: "Clean generator from the 1Password team",
        pros: ["Clean interface", "Memorable password option", "Trusted brand"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "LastPass Password Generator",
        path: "https://lastpass.com/generatepassword.php",
        tagline: "Quick generator from LastPass, works without account",
        pros: ["No account needed", "Length and complexity control", "Avoids ambiguous characters"],
        free: true,
        accountRequired: false,
      },
    ],
  },
  {
    slug: "image-converters",
    title: "Best Free Online Image Converters",
    metaTitle: "Best Free Image Converters Online in 2026 — JPG, PNG, WebP, AVIF",
    metaDescription: "The best free online image converters compared: supported formats, file size limits, privacy, and whether images are uploaded to external servers.",
    primaryKeyword: "best free image converter online",
    description: "Compare the top free image format converters by supported formats, batch conversion, privacy, and speed.",
    tools: [
      {
        rank: 1,
        name: "TheFreeAITools — Image Converter",
        path: "/tools/image-converter",
        tagline: "Convert JPG, PNG, WebP, AVIF in browser — no upload, no account",
        pros: ["No account required", "Files never uploaded", "No batch limit", "AVIF and WebP support"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 2,
        name: "Convertio",
        path: "https://convertio.co",
        tagline: "300+ format support including video, audio, and documents",
        pros: ["300+ formats", "Cloud storage integration", "API available", "Batch conversion"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 3,
        name: "CloudConvert",
        path: "https://cloudconvert.com",
        tagline: "High-quality conversions with 200+ format support",
        pros: ["High quality output", "200+ formats", "API available", "Advanced options"],
        free: true,
        accountRequired: false,
      },
      {
        rank: 4,
        name: "Squoosh",
        path: "https://squoosh.app",
        tagline: "Google's browser-based image codec converter",
        pros: ["Local processing", "Advanced codec control", "WebP and AVIF", "No upload"],
        free: true,
        accountRequired: false,
      },
    ],
  },
]

export function getBestCategory(slug: string): BestCategory | undefined {
  return BEST_CATEGORIES.find((c) => c.slug === slug)
}

export function getAllBestSlugs(): { category: string }[] {
  return BEST_CATEGORIES.map((c) => ({ category: c.slug }))
}
