export interface UseCase {
  slug: string
  title: string
  metaTitle: string
  metaDescription: string
  primaryKeyword: string
  intro: string
  toolId: string
  toolName: string
  toolPath: string
  steps: { title: string; detail: string }[]
  whoItsFor: { role: string; scenario: string }[]
  faq: { q: string; a: string }[]
}

export const USE_CASES: UseCase[] = [
  {
    slug: "detect-ai-essay",
    title: "How to Detect AI-Written Essays",
    metaTitle: "How to Detect AI-Written Essays — Free AI Detector for Students & Teachers",
    metaDescription: "Detect AI-written essays instantly with our free AI text detector. No account needed. Identify ChatGPT, Claude, and Gemini content in student submissions.",
    primaryKeyword: "detect ai written essays",
    intro: "AI writing in academic submissions is at an all-time high. This guide explains how to detect AI-written essays using perplexity and burstiness analysis — and what to do next.",
    toolId: "detect-text-ai",
    toolName: "Free AI Text Detector",
    toolPath: "/tools/detect-text-ai",
    steps: [
      { title: "Copy the submission text", detail: "Open the essay or submission and copy the full text. The detector works best with 100+ words." },
      { title: "Paste into the AI detector", detail: "Paste the text into the input field at the top of this page." },
      { title: "Click 'Detect AI Content'", detail: "No login required. The tool cross-validates against multiple AI models." },
      { title: "Review the probability score", detail: "Scores above 70% indicate strong AI authorship. Scores below 35% suggest human writing." },
      { title: "Check the Charts tab", detail: "Visual charts show perplexity and burstiness patterns that reveal AI generation signals sentence-by-sentence." },
    ],
    whoItsFor: [
      { role: "Teachers & Professors", scenario: "Screen student essays before grading. Flag high-scoring submissions for further review." },
      { role: "Academic Administrators", scenario: "Audit submitted coursework at scale for AI policy compliance." },
      { role: "Students", scenario: "Check your own AI-assisted drafts before submission to ensure they meet your institution's AI policy." },
    ],
    faq: [
      { q: "Can this detect essays written with ChatGPT?", a: "Yes. The tool is specifically calibrated for ChatGPT, Claude, Gemini, and other major models. It uses perplexity scoring to detect the predictable word patterns that AI models produce." },
      { q: "Is this AI essay detector free?", a: "Yes. TheFreeAITools provides free AI detection with no account required. Rate limits apply to ensure fair access." },
      { q: "How accurate is AI essay detection?", a: "High accuracy on clearly AI-generated content, moderate accuracy on heavily edited or humanized text. No tool is 100% accurate — use scores as one signal among many." },
    ],
  },
  {
    slug: "humanize-ai-for-teachers",
    title: "How to Make AI Text Sound Human (For Students)",
    metaTitle: "How to Humanize AI Text for School — Bypass AI Detectors Free",
    metaDescription: "Rewrite AI-generated text to sound natural and pass AI detectors like GPTZero and Turnitin. Free, no account. Preserves your original meaning.",
    primaryKeyword: "humanize ai text for school",
    intro: "Need to use AI as a writing aid but want to ensure your final submission sounds authentically human? This guide covers how to effectively humanize AI-generated content while preserving your message.",
    toolId: "clean-text-using-ai",
    toolName: "Free AI Text Humanizer",
    toolPath: "/tools/clean-text-using-ai",
    steps: [
      { title: "Draft your content with AI", detail: "Use ChatGPT, Claude, or Gemini to create an initial draft on your topic." },
      { title: "Paste the draft into the humanizer", detail: "Copy your AI draft and paste it into the text input." },
      { title: "Click 'Clean Text'", detail: "The AI rewrites your content with varied sentence lengths, richer vocabulary, and natural flow." },
      { title: "Review and edit personally", detail: "Read through the humanized output. Add your own specific details, examples, and voice." },
      { title: "Run through the AI detector first", detail: "Use our free AI detector to verify the score before submitting." },
    ],
    whoItsFor: [
      { role: "Students", scenario: "Use AI for research and drafting, then humanize and edit to meet academic integrity standards." },
      { role: "Content Writers", scenario: "Use AI for initial outlines, then humanize to match your publication's editorial voice." },
      { role: "Marketing Teams", scenario: "Generate AI copy variations, humanize them, then QA before publishing." },
    ],
    faq: [
      { q: "Will humanized text always pass AI detectors?", a: "Humanizing significantly reduces AI detection scores but is not guaranteed to pass every detector. The best approach is to also add your own edits, examples, and personal voice after humanizing." },
      { q: "Does humanizing change the meaning of my text?", a: "No. The humanizer is specifically instructed to preserve your original meaning, facts, and context while changing only the stylistic delivery." },
      { q: "Is the AI humanizer free?", a: "Yes. TheFreeAITools provides free humanization with no account required." },
    ],
  },
  {
    slug: "convert-python-to-javascript",
    title: "How to Convert Python Code to JavaScript",
    metaTitle: "Convert Python to JavaScript Free — AI Code Converter Online",
    metaDescription: "Convert Python code to JavaScript instantly with AI. Handles lists to arrays, dict to objects, async patterns, and more. Free, no account needed.",
    primaryKeyword: "convert python to javascript",
    intro: "Converting Python to JavaScript involves more than syntax changes — you need to handle type differences, iteration patterns, and async behavior. Our AI code converter handles this automatically.",
    toolId: "code-converter",
    toolName: "Free Code Converter",
    toolPath: "/tools/code-converter",
    steps: [
      { title: "Select Python as the source language", detail: "Use the language selector on the left side of the converter." },
      { title: "Select JavaScript as the target", detail: "Use the language selector on the right, or click the Python→JS quick-select button." },
      { title: "Paste your Python code", detail: "Copy your Python script or function and paste it into the input field." },
      { title: "Click 'Convert Code'", detail: "The AI converts your code with idiomatic JavaScript patterns, not just syntax substitution." },
      { title: "Review the conversion notes", detail: "The output includes notes on key differences like list comprehensions, dict access, and async patterns." },
    ],
    whoItsFor: [
      { role: "Backend Developers", scenario: "Migrate Python API logic to a Node.js backend without rewriting from scratch." },
      { role: "Data Scientists", scenario: "Port Python data processing scripts to JavaScript for browser-based visualization." },
      { role: "Students", scenario: "Understand how the same algorithm looks in different languages — great for learning." },
    ],
    faq: [
      { q: "Does the converter handle Python-specific features like list comprehensions?", a: "Yes. The AI converts Python list comprehensions to equivalent JavaScript .map(), .filter(), and .reduce() calls, not just literal syntax substitution." },
      { q: "Can I convert async Python code to JavaScript?", a: "Yes. Python async/await maps directly to JavaScript async/await. The converter handles this correctly in most cases." },
      { q: "Is the Python to JavaScript converter free?", a: "Yes. Completely free with no account required." },
    ],
  },
  {
    slug: "fix-javascript-errors",
    title: "How to Fix JavaScript Errors Online",
    metaTitle: "Fix JavaScript Errors Online Free — AI Error Solver for JS & Node.js",
    metaDescription: "Paste any JavaScript or Node.js error message and get an instant root cause analysis with step-by-step fix. Supports React, Next.js, Express, and more.",
    primaryKeyword: "fix javascript errors online",
    intro: "JavaScript errors can be cryptic — 'Cannot read properties of undefined', 'Uncaught TypeError', ReferenceError. Our AI error solver diagnoses the root cause and tells you exactly how to fix it.",
    toolId: "error-message-solver",
    toolName: "Free Error Message Solver",
    toolPath: "/tools/error-message-solver",
    steps: [
      { title: "Copy your full error message", detail: "Include the complete stack trace from your browser console or Node.js terminal — more context = better diagnosis." },
      { title: "Select JavaScript or your framework", detail: "Choose React, Next.js, Node.js, Express, or TypeScript for targeted fixes." },
      { title: "Paste the error and click 'Solve'", detail: "The AI analyzes the stack trace and identifies the root cause." },
      { title: "Apply the step-by-step fix", detail: "Follow the fix instructions. The output includes corrected code you can drop directly into your project." },
      { title: "Test and verify", detail: "Run your code again to confirm the error is resolved." },
    ],
    whoItsFor: [
      { role: "Frontend Developers", scenario: "Debug React component errors, hook violations, and prop type issues instantly." },
      { role: "Node.js Developers", scenario: "Diagnose Express middleware errors, async unhandled rejections, and module resolution failures." },
      { role: "Students Learning JavaScript", scenario: "Understand why your code fails, not just how to suppress the error." },
    ],
    faq: [
      { q: "Can this fix Next.js errors too?", a: "Yes. Select 'Next.js' in the framework dropdown and the AI will give fixes specific to Next.js routing, server components, API routes, and build errors." },
      { q: "Does it work with TypeScript errors?", a: "Yes. Paste TypeScript compiler errors (TS2345, TS2339, etc.) and the AI explains the type conflict and how to resolve it." },
      { q: "Is the error solver free?", a: "Yes. Completely free with no account required." },
    ],
  },
  {
    slug: "generate-ai-images-free",
    title: "How to Generate AI Images for Free (No Account)",
    metaTitle: "Generate AI Images Free — No Account, No Watermark, No Limits",
    metaDescription: "Generate AI images for free with no account required. Uses the Flux model. Enter a text prompt and get high-quality images instantly.",
    primaryKeyword: "generate ai images free",
    intro: "Most AI image generators require you to create an account, buy credits, or accept watermarks. Our free AI image generator skips all of that — enter a prompt, get your image.",
    toolId: "free-ai-image-generator",
    toolName: "Free AI Image Generator",
    toolPath: "/tools/free-ai-image-generator",
    steps: [
      { title: "Write a descriptive text prompt", detail: "Be specific: include subject, style, lighting, mood, and composition. Example: 'A futuristic cityscape at night, neon lights reflecting in rain, cinematic, photorealistic'." },
      { title: "Select your image dimensions", detail: "Choose aspect ratio: square (1:1), landscape (16:9), portrait (9:16), or widescreen." },
      { title: "Click 'Generate Image'", detail: "The Flux model generates your image in seconds. No login required." },
      { title: "Download or regenerate", detail: "Download your image directly. If you don't like the result, adjust your prompt and generate again." },
    ],
    whoItsFor: [
      { role: "Content Creators", scenario: "Create unique blog post images, social media visuals, and thumbnails without paying for stock photos." },
      { role: "Developers", scenario: "Generate placeholder images for mockups and prototypes without leaving the browser." },
      { role: "Students & Hobbyists", scenario: "Explore generative AI art without signing up for Midjourney or DALL-E." },
    ],
    faq: [
      { q: "What AI model does this use?", a: "The free image generator uses the Flux model, which produces high-quality, photorealistic and artistic images from text prompts." },
      { q: "Are there watermarks on the generated images?", a: "No watermarks. You own the images you generate." },
      { q: "Is it really free with no account?", a: "Yes. No account, no credit card, no credits system. Just enter your prompt and generate." },
    ],
  },
  {
    slug: "paraphrase-essay-free",
    title: "How to Paraphrase an Essay for Free",
    metaTitle: "Paraphrase Essay Free — AI Paraphrasing Tool No Account Needed",
    metaDescription: "Paraphrase any essay, paragraph, or article with AI. Avoid plagiarism and improve readability. Multiple tones available. Free, no account.",
    primaryKeyword: "paraphrase essay free",
    intro: "Paraphrasing an essay means rewriting it in your own words while preserving the original meaning. Our free AI paraphrasing tool does this in seconds — across 5 different tones.",
    toolId: "ai-paraphrasing-tool-and-rewriter",
    toolName: "Free AI Paraphrasing Tool",
    toolPath: "/tools/ai-paraphrasing-tool-and-rewriter",
    steps: [
      { title: "Copy the essay text you want to paraphrase", detail: "Select all or paste specific paragraphs you want to rewrite." },
      { title: "Paste it into the paraphrasing tool", detail: "The tool accepts essays, articles, paragraphs, and individual sentences." },
      { title: "Select a tone", detail: "Choose Standard, Formal, Fluent, Simple, or Creative depending on your goal." },
      { title: "Click 'Rewrite Text'", detail: "The AI rewrites your content with different vocabulary and sentence structure." },
      { title: "Review and use", detail: "Read the output, make any personal adjustments, and copy to use." },
    ],
    whoItsFor: [
      { role: "Students", scenario: "Rephrase source material for research papers without plagiarizing. Always cite your sources." },
      { role: "Content Marketers", scenario: "Repurpose blog posts and articles into fresh versions for different audiences." },
      { role: "ESL Writers", scenario: "Improve the English fluency of your writing by rephrasing in the Fluent tone." },
    ],
    faq: [
      { q: "Is paraphrasing the same as plagiarism?", a: "Paraphrasing source material without citation is still plagiarism. Use this tool to improve your writing style and clarity — always cite your sources." },
      { q: "What tones are available?", a: "Standard (neutral), Formal (academic/professional), Fluent (smooth and readable), Simple (easy language), and Creative (varied and expressive)." },
      { q: "Is the paraphrasing tool free?", a: "Yes. Completely free with no account required." },
    ],
  },
  {
    slug: "explain-code-beginners",
    title: "How to Understand Code as a Beginner",
    metaTitle: "Free Code Explainer for Beginners — Understand Any Code with AI",
    metaDescription: "Paste any code snippet and get a plain-English explanation. Perfect for beginners learning Python, JavaScript, Java, or any language. Free, no account.",
    primaryKeyword: "code explainer for beginners",
    intro: "Reading other people's code (or AI-generated code) is one of the hardest skills for beginners. Our AI code explainer translates any snippet into plain English — at your skill level.",
    toolId: "code-explainer",
    toolName: "Free Code Explainer",
    toolPath: "/tools/code-explainer",
    steps: [
      { title: "Find the code you don't understand", detail: "This could be a function from a tutorial, an AI-generated snippet, or code from Stack Overflow." },
      { title: "Paste the code into the explainer", detail: "The tool accepts code in any language — it auto-detects the language." },
      { title: "Select 'Beginner' explanation level", detail: "This gives you the simplest, jargon-free explanation. Switch to Intermediate or Expert as you grow." },
      { title: "Click 'Explain Code'", detail: "The AI explains what the code does, what each part means, and why it's written that way." },
      { title: "Read the key concepts section", detail: "This section explains any programming concepts (like loops, recursion, or async) that appear in your code." },
    ],
    whoItsFor: [
      { role: "Programming Beginners", scenario: "Understand tutorials and examples without getting stuck on unfamiliar syntax." },
      { role: "Career Changers", scenario: "Decode legacy code at a new job when you don't have time to ask colleagues." },
      { role: "Students", scenario: "Understand homework examples and lab code more deeply than surface-level." },
    ],
    faq: [
      { q: "What programming languages does this support?", a: "22+ languages including Python, JavaScript, TypeScript, Java, C++, C#, Go, Rust, PHP, Ruby, Swift, Kotlin, SQL, HTML, CSS, and more. It also auto-detects the language." },
      { q: "Can it explain AI-generated code?", a: "Yes. If you generated code with ChatGPT or Copilot and don't understand what it does, paste it here for a clear explanation." },
      { q: "Is the code explainer free?", a: "Yes. Completely free with no account required." },
    ],
  },
  {
    slug: "convert-image-to-pdf-for-submission",
    title: "How to Convert an Image to PDF for Form Submissions",
    metaTitle: "Convert Image to PDF for Free — No Account, No App Download",
    metaDescription: "Convert photos and screenshots to PDF for form submissions, job applications, and document uploads. Free, browser-based, no account required.",
    primaryKeyword: "convert image to pdf free",
    intro: "Many forms, job application portals, and government websites only accept PDF uploads — not JPG or PNG. This guide covers how to convert any image to a proper PDF document in under 30 seconds, free, with no account.",
    toolId: "convert-image-to-pdf",
    toolName: "Image to PDF Converter",
    toolPath: "/tools/convert-image-to-pdf",
    steps: [
      { title: "Open the Image to PDF Converter", detail: "Go to the free image to PDF converter — no account or sign-up required." },
      { title: "Upload your image", detail: "Upload a JPG, PNG, or WebP image. Photos of documents, screenshots, or scans all work." },
      { title: "Select the page size", detail: "Choose A4 for international submissions or Letter for US. Choose 'Fit to image' to avoid white borders." },
      { title: "Click Convert", detail: "Your image is converted to a PDF in your browser — no file is uploaded to any server." },
      { title: "Download and submit the PDF", detail: "Download the PDF file and upload it to your submission portal, email it, or attach it to a form." },
    ],
    whoItsFor: [
      { role: "Job Applicants", scenario: "Convert a photo of a signed document, ID, or certificate to PDF for online job application portals that require PDF format." },
      { role: "Students", scenario: "Convert handwritten assignment photos to PDF for submission through university portals that require PDF format." },
      { role: "Small Business Owners", scenario: "Convert product photos or signed contracts photographed with a phone to PDF for client and vendor submissions." },
    ],
    faq: [
      { q: "Will the image quality be preserved in the PDF?", a: "Yes. The image is embedded in the PDF at its original resolution. There is no quality loss in the conversion — the PDF contains your image exactly as uploaded." },
      { q: "Can I convert a phone photo to PDF?", a: "Yes. Photos taken on any smartphone (JPG or HEIC format) can be converted. If your phone saves photos as HEIC, convert to JPG first using the image converter, then convert to PDF." },
      { q: "What is the maximum image size I can convert?", a: "The converter processes images locally in your browser — there is no server-side file size limit. Images up to several hundred MB convert without issues on modern devices." },
      { q: "Can I put multiple images in one PDF?", a: "The current tool converts one image per PDF. To combine multiple images into a single PDF, convert each to PDF individually, then merge the PDF files using a tool like iLovePDF's free merge feature." },
    ],
  },
  {
    slug: "check-website-ssl-expiry",
    title: "How to Check a Website's SSL Certificate Expiry Date",
    metaTitle: "Check SSL Certificate Expiry Free — SSL Checker Online",
    metaDescription: "Check any website's SSL certificate expiry date, issuer, and validity instantly. Free, no account required. Get an alert before your cert expires.",
    primaryKeyword: "check ssl certificate expiry",
    intro: "An expired SSL certificate takes your website offline for all users — browsers block access and show a full-page warning. This guide covers how to check any website's SSL expiry date before it expires, and what to do if it already has.",
    toolId: "ssl-checker",
    toolName: "Free SSL Checker",
    toolPath: "/tools/ssl-checker",
    steps: [
      { title: "Open the SSL Checker", detail: "Go to the free SSL checker — no account required." },
      { title: "Enter the domain name", detail: "Type the domain without https:// — for example: yourdomain.com. The tool checks both www and non-www automatically." },
      { title: "Click Check SSL", detail: "The tool connects to the domain, retrieves the SSL certificate, and shows the full details." },
      { title: "Review the expiry date", detail: "The expiry date and days remaining are shown prominently. Check the issuer to confirm it is a trusted Certificate Authority." },
      { title: "Set a renewal reminder", detail: "Set a calendar reminder 30 days before the expiry date. For Let's Encrypt certificates (90-day expiry), set a reminder at 60 days." },
    ],
    whoItsFor: [
      { role: "Website Owners", scenario: "Check your own site's SSL certificate before it expires — an expired cert blocks all visitors and damages SEO." },
      { role: "Developers", scenario: "Verify that an SSL certificate was correctly installed after renewal or a hosting change." },
      { role: "IT & Security Teams", scenario: "Audit SSL expiry across all company domains to prevent unexpected outages from certificate expiration." },
    ],
    faq: [
      { q: "What happens when an SSL certificate expires?", a: "All major browsers (Chrome, Firefox, Safari, Edge) show a full-page warning blocking access to the site. Most users will not proceed past this warning. Search rankings drop because Google cannot crawl HTTPS sites with invalid certificates." },
      { q: "How often should I check my SSL certificate?", a: "Check monthly if you manage your own certificate renewal. If your hosting platform auto-renews (Cloudflare, most managed hosting), check quarterly to verify auto-renewal is working correctly." },
      { q: "How do I renew an SSL certificate for free?", a: "Let's Encrypt provides free SSL certificates that auto-renew every 90 days when set up correctly via Certbot (Linux servers), Cloudflare (free plan), or most managed hosting platforms. If your certificate expired, check why the auto-renewal failed — usually a configuration issue." },
      { q: "Can I check an SSL certificate that is already expired?", a: "Yes. The SSL checker will show the certificate details including the expired date even if the certificate is no longer valid. This helps you understand when it expired and who issued it so you can renew with the same provider." },
    ],
  },
  {
    slug: "format-validate-json-api-debugging",
    title: "How to Format and Validate JSON for API Debugging",
    metaTitle: "Format JSON Online Free — Validate & Debug API Responses",
    metaDescription: "Format, validate, and debug JSON from API responses in your browser. Free JSON formatter with syntax highlighting — no account, no server upload.",
    primaryKeyword: "format json online free",
    intro: "When an API returns malformed JSON or a dense minified payload that is impossible to read, a good JSON formatter is the fastest debugging tool available. This guide covers how to format and validate API JSON responses in seconds, with common error fixes.",
    toolId: "json-formatter",
    toolName: "Free JSON Formatter",
    toolPath: "/tools/json-formatter",
    steps: [
      { title: "Open the JSON Formatter", detail: "Go to the free JSON formatter — no account required." },
      { title: "Paste your JSON", detail: "Copy the API response from your browser's Network tab, Postman, or curl output, and paste it into the formatter." },
      { title: "Click Format", detail: "Valid JSON is formatted with 2-space indentation, syntax highlighting for keys, strings, numbers, and booleans, and collapsible sections for nested objects." },
      { title: "Read the error message if invalid", detail: "If the JSON is malformed, the formatter shows the exact error position — line number and character. Common errors: trailing commas, single quotes, and unescaped special characters." },
      { title: "Minify for production", detail: "To reduce payload size, click Minify to produce the most compact valid JSON representation." },
    ],
    whoItsFor: [
      { role: "Backend Developers", scenario: "Quickly inspect API response payloads during development without switching to Postman or a separate JSON viewer." },
      { role: "Frontend Developers", scenario: "Format API responses copied from browser DevTools Network tab to understand the data structure before writing fetch logic." },
      { role: "QA Engineers", scenario: "Validate that API responses are well-formed JSON before testing response content." },
    ],
    faq: [
      { q: "Is my API response data sent to any server?", a: "No. The JSON formatter processes all input locally in your browser using JavaScript. API responses containing authentication tokens, user data, or business information are never transmitted to any external server." },
      { q: "What JSON errors does the formatter detect?", a: "Trailing commas, single quotes instead of double quotes, unescaped backslashes and special characters, invalid number formats (NaN, Infinity), mismatched braces and brackets, and missing commas between properties." },
      { q: "Can I format JSON from a file rather than pasting?", a: "The formatter accepts pasted text. For large JSON files, open the file in a text editor, select all, copy, and paste into the formatter. Files up to several MB format without issues in most browsers." },
      { q: "What is the difference between formatting and validating JSON?", a: "Formatting (pretty-printing) adds indentation and line breaks to make JSON readable — it works only on valid JSON. Validation checks whether the JSON structure is correct according to the JSON specification and reports errors with position if not." },
    ],
  },
  {
    slug: "compress-image-for-website",
    title: "How to Compress Images for a Website",
    metaTitle: "Compress Images for Website — Free Online, No Quality Loss",
    metaDescription: "Compress JPEG, PNG, and WebP images for faster website load times. Free browser-based tool — no account, no upload limit, no quality loss.",
    primaryKeyword: "compress image for website",
    intro: "Large images are the number-one cause of slow website load times. This guide covers how to compress images to the right size for web use — the quality level that looks perfect on screen, the format that gives the smallest file, and the resize step most guides skip.",
    toolId: "image-compressor",
    toolName: "Free Image Compressor",
    toolPath: "/tools/image-compressor",
    steps: [
      { title: "Open the Image Compressor", detail: "Go to the free image compressor — no account or sign-up required." },
      { title: "Upload your image", detail: "Drag and drop or click to upload your JPEG, PNG, or WebP file." },
      { title: "Set the quality level", detail: "For photos, 80–85% quality is the sweet spot — visually indistinguishable from the original but 60–70% smaller." },
      { title: "Check the output file size", detail: "The tool shows the compressed file size in real time. Aim for under 200 KB for most web images, under 100 KB for thumbnails." },
      { title: "Download the compressed image", detail: "Download and replace your original. Re-upload to your CMS or website builder." },
    ],
    whoItsFor: [
      { role: "Website Owners", scenario: "Reduce page load time without a developer by compressing images before uploading to WordPress, Shopify, or Squarespace." },
      { role: "Bloggers", scenario: "Compress featured images and inline photos before publishing to keep posts loading fast on mobile." },
      { role: "E-commerce Sellers", scenario: "Compress product photos to keep category pages fast — especially important on mobile where conversion rates drop with each second of load time." },
    ],
    faq: [
      { q: "What file size should web images be?", a: "For hero/banner images: under 300 KB. For blog post images: under 200 KB. For thumbnails and icons: under 50 KB. These are guidelines — the goal is pages that load in under 3 seconds on a mobile connection." },
      { q: "Does compressing images affect SEO?", a: "Yes, positively. Google's Core Web Vitals score includes Largest Contentful Paint (LCP), which is heavily influenced by image loading speed. Smaller images improve LCP scores and can improve search rankings." },
      { q: "What quality setting should I use for web?", a: "80–85% quality for JPEG produces images that look identical to the original at normal viewing sizes on screen. For PNG (lossless format), compression is about removing metadata and optimizing data structure rather than a quality slider." },
      { q: "Should I use JPG or WebP for websites?", a: "WebP is the better choice for modern websites — it is 25–35% smaller than JPEG at equivalent quality and is supported by all major browsers. Use JPEG as a fallback for email and external use where WebP may not be supported." },
    ],
  },
  {
    slug: "remove-background-product-photo",
    title: "How to Remove the Background from a Product Photo",
    metaTitle: "Remove Background from Product Photo Free — No Photoshop, No Account",
    metaDescription: "Remove image backgrounds from product photos instantly. Free browser-based tool — no Photoshop, no account, no upload to external servers.",
    primaryKeyword: "remove background product photo",
    intro: "A product photo with a clean transparent or white background is the standard for e-commerce, marketplaces, and presentations. This guide covers how to remove backgrounds for free in under 10 seconds — no Photoshop skills required.",
    toolId: "remove-bg",
    toolName: "Free Background Remover",
    toolPath: "/tools/remove-bg",
    steps: [
      { title: "Open the Background Remover", detail: "Go to the free background remover — no account required." },
      { title: "Upload your product photo", detail: "Upload a JPEG or PNG of your product. Photos with good contrast between the product and background get the best results." },
      { title: "Wait for AI processing", detail: "The AI identifies your product and removes the background in 1–3 seconds. Processing runs in your browser — your image is never uploaded." },
      { title: "Preview the transparent background", detail: "The background shows as a checkerboard pattern — this is the transparent area. Check edges around the product for accuracy." },
      { title: "Download the PNG", detail: "Download the transparent PNG. For a white background (required by Amazon and most marketplaces), open in any image editor and add a white layer behind the subject." },
    ],
    whoItsFor: [
      { role: "E-commerce Sellers", scenario: "Prepare product photos for Amazon, Etsy, eBay, and Shopify listings that require white backgrounds — without hiring a photographer or Photoshop expert." },
      { role: "Small Business Owners", scenario: "Remove backgrounds from product shots taken on any surface for use in marketing materials, social posts, and online stores." },
      { role: "Freelancers", scenario: "Quickly batch-process client product photos for catalog pages and promotional materials." },
    ],
    faq: [
      { q: "Does Amazon require a white background for product photos?", a: "Yes. Amazon's main product image requirements specify a pure white background (RGB 255, 255, 255), with the product filling 85%+ of the frame. After removing the background, open the transparent PNG in any image editor and add a white fill layer behind it." },
      { q: "What type of products work best with AI background removal?", a: "Products with clear edges and good contrast against their background work best — packaged goods, electronics, clothing on mannequins, and most solid objects. Transparent products (glass, bottles) and very fine details (jewelry, thin straps) are harder for AI to cut accurately." },
      { q: "Is my product photo uploaded to any server?", a: "No. The background remover at thefreeaitools.com processes images locally in your browser using on-device AI. Your product photos are never transmitted to any server." },
      { q: "What if the edges look jagged or inaccurate?", a: "For difficult edges, the best fix is improving the source photo: use a contrasting background when photographing (a sheet of colored paper works), ensure good even lighting, and use a camera with enough resolution to capture edge detail." },
    ],
  },
  {
    slug: "generate-qr-code-for-business",
    title: "How to Generate a QR Code for Your Business",
    metaTitle: "Generate QR Code for Business Free — No Account, No Expiry",
    metaDescription: "Create permanent QR codes for websites, menus, business cards, and more. Free, no account required. QR codes never expire.",
    primaryKeyword: "generate qr code for business",
    intro: "QR codes on business cards, menus, packaging, and marketing materials let customers jump directly to your website, menu, or contact page. This guide covers how to create one free in under 60 seconds — the size settings for print, the format to use, and why free QR codes don't have to expire.",
    toolId: "qr-code-generator",
    toolName: "Free QR Code Generator",
    toolPath: "/tools/qr-code-generator",
    steps: [
      { title: "Open the QR Code Generator", detail: "Go to the free QR code generator — no account required." },
      { title: "Enter your URL or content", detail: "Paste your website URL, menu link, contact page, or any URL you want the QR code to point to. For best results, use a short URL or link shortener first." },
      { title: "Choose the error correction level", detail: "Select 'High' (30%) if you plan to add a logo in the center of the QR code, or if the code will be printed on uneven surfaces. 'Medium' (15%) is fine for most uses." },
      { title: "Download your QR code", detail: "Download as PNG for digital use or SVG for print. SVG scales to any size without quality loss." },
      { title: "Test the QR code before printing", detail: "Scan your downloaded QR code with a phone before sending it to print. Verify it opens the correct URL." },
    ],
    whoItsFor: [
      { role: "Restaurant & Cafe Owners", scenario: "Link QR codes on tables to your digital menu — no printing costs when the menu changes." },
      { role: "Small Business Owners", scenario: "Add a QR code to business cards and flyers pointing to your website, booking page, or Google Business profile." },
      { role: "Event Organizers", scenario: "Place QR codes on event materials linking to registration pages, schedules, or maps." },
    ],
    faq: [
      { q: "Do free QR codes expire?", a: "QR codes generated at thefreeaitools.com never expire — they point directly to your URL and work as long as that URL is live. Unlike paid 'dynamic' QR code services, there is no subscription required to keep the code active." },
      { q: "What size should a QR code be for print?", a: "The minimum recommended size for reliable scanning is 2 cm × 2 cm (about 0.8 inch × 0.8 inch). For business cards, 2.5–3 cm is comfortable. For posters and signage, larger is better. Download the SVG version for print — it scales to any size without pixelation." },
      { q: "Can I put a logo in the center of the QR code?", a: "Yes. QR codes have built-in error correction that allows up to 30% of the code to be obscured while still scanning correctly. Select 'High' error correction level, then overlay your logo in the center — keep it under 25% of the total code area." },
      { q: "What if my URL changes after I print the QR code?", a: "A static QR code points directly to the URL you entered — if that URL changes, the code breaks. To avoid this, point the QR code to a URL you control (your own domain) and redirect from there. Or use a URL shortener that lets you update the destination." },
    ],
  },
  {
    slug: "compress-image-for-email",
    title: "How to Compress an Image for Email",
    metaTitle: "How to Compress an Image for Email — Free, No Account",
    metaDescription: "Compress images for email attachments in seconds. Reduce JPEG and PNG files below 1MB without visible quality loss. Free, browser-based, no account needed.",
    primaryKeyword: "compress image for email attachment",
    intro: "Most email clients reject attachments over 10–25MB, and large image attachments slow down inboxes. This guide shows how to compress any image to a size suitable for email — fast, free, and without installing software.",
    toolId: "image-compressor",
    toolName: "Free Image Compressor",
    toolPath: "/tools/image-compressor",
    steps: [
      { title: "Open the image compressor", detail: "No account or installation needed — the tool runs entirely in your browser." },
      { title: "Upload your image", detail: "Click 'Upload' or drag and drop your JPEG, PNG, or WebP file. Files stay in your browser and are never uploaded to a server." },
      { title: "Set the quality slider", detail: "Start at 80% quality. For email thumbnails, 70% is often sufficient. The preview updates in real time." },
      { title: "Check the compressed file size", detail: "Most photos compress from 3–8MB down to 200–600KB at 80% quality — well within any email attachment limit." },
      { title: "Download and attach", detail: "Click 'Download' to save the compressed image, then attach it to your email as usual." },
    ],
    whoItsFor: [
      { role: "Business professionals", scenario: "Sending product photos, event images, or presentation screenshots via email without hitting attachment size limits." },
      { role: "Photographers", scenario: "Sharing portfolio previews or client proofs via email before delivering full-resolution files separately." },
      { role: "Teachers and students", scenario: "Attaching assignment screenshots or scanned document images that need to stay under school email limits." },
    ],
    faq: [
      { q: "What is a good image size for email attachments?", a: "Keep each image under 1MB for reliable delivery. Most email clients accept attachments up to 10–25MB total, but large images slow delivery and fill recipients' inboxes. A compressed 80%-quality JPEG of a typical smartphone photo is 200–400KB — good for email." },
      { q: "Will compressing reduce visible image quality?", a: "At 80% quality, visible quality loss is minimal on most photos. The tool shows a before/after preview so you can confirm the result before downloading." },
      { q: "What formats does the image compressor support?", a: "The compressor supports JPEG, PNG, and WebP. For email, JPEG is the best format — it achieves the smallest file size for photographs." },
    ],
  },
  {
    slug: "convert-png-to-jpg",
    title: "How to Convert PNG to JPG Without Losing Quality",
    metaTitle: "How to Convert PNG to JPG Free Online — No Quality Loss",
    metaDescription: "Convert PNG to JPG in your browser — free, no account, no upload. Reduce file size by up to 80% with adjustable quality.",
    primaryKeyword: "convert png to jpg without losing quality",
    intro: "PNG files can be 3–5× larger than the equivalent JPEG, which slows page loads and fills storage. This guide explains how to convert PNG to JPG with the best quality-to-size ratio — free, with no software needed.",
    toolId: "image-converter",
    toolName: "Free Image Converter",
    toolPath: "/tools/image-converter",
    steps: [
      { title: "Open the image converter", detail: "No account or installation needed. The converter runs in your browser." },
      { title: "Upload your PNG file", detail: "Click 'Upload' or drag and drop. Supports PNG files of any size." },
      { title: "Select JPG as the output format", detail: "Choose JPEG / JPG from the format dropdown." },
      { title: "Set the quality level", detail: "80–85% quality produces the best balance: photos are visually identical to the original but 60–80% smaller in file size." },
      { title: "Download the JPG", detail: "Click 'Convert' and download the resulting JPG file. The original PNG is unchanged." },
    ],
    whoItsFor: [
      { role: "Web developers", scenario: "Replacing heavy PNG photos on websites with JPEGs to improve page load speed and Core Web Vitals scores." },
      { role: "Content creators", scenario: "Converting PNG screenshots or illustrations exported from design tools to web-ready JPEGs for upload." },
      { role: "Social media managers", scenario: "Reducing image file sizes before uploading to platforms that compress images on their own, preserving more quality." },
    ],
    faq: [
      { q: "Does converting PNG to JPG lose quality?", a: "JPEG is a lossy format, so there is some quality reduction. At 80–85% quality, the difference is invisible to the eye on photographs. For logos, text, and graphics with sharp edges, PNG is better — JPEG creates visible compression artifacts on those." },
      { q: "Why is my PNG file so much larger than JPG?", a: "PNG is lossless — it stores every pixel exactly. JPEG discards some pixel data using perceptual compression. For photographs, this trade-off is nearly invisible but produces files 60–80% smaller." },
      { q: "Can I convert multiple PNGs to JPG at once?", a: "The image converter supports individual conversions. For bulk conversion, process files one at a time or use a desktop tool like ImageMagick for batch operations." },
    ],
  },
  {
    slug: "check-if-text-is-ai-written",
    title: "How to Check If Text Is AI Written",
    metaTitle: "How to Check If Text Is AI Written — Free AI Detector Online",
    metaDescription: "Check if any text was written by ChatGPT, Claude, or Gemini with our free AI detector. No account, instant results, no character limit.",
    primaryKeyword: "how to check if text is ai written",
    intro: "AI-generated text now appears in academic submissions, news articles, job applications, and content at scale. This guide explains how AI detectors work and how to check any text for AI authorship — free and without an account.",
    toolId: "detect-text-ai",
    toolName: "Free AI Text Detector",
    toolPath: "/tools/detect-text-ai",
    steps: [
      { title: "Copy the text you want to check", detail: "Select all the text from the document, email, or submission and copy it. The detector works best with 100+ words." },
      { title: "Paste into the AI detector", detail: "Open the free AI text detector and paste the text into the input field. No account or sign-in is required." },
      { title: "Click 'Detect AI Content'", detail: "The tool analyzes perplexity (how predictable the word choices are) and burstiness (variation in sentence length) — both signals of AI generation." },
      { title: "Review the probability score", detail: "Scores above 70% indicate strong AI authorship. Scores below 30% suggest human writing. The 30–70% range often indicates AI-assisted or heavily edited content." },
      { title: "Check the sentence-level breakdown", detail: "The detailed view highlights individual sentences scored as likely AI-generated, helping you identify which parts of the text are suspicious." },
    ],
    whoItsFor: [
      { role: "Teachers and professors", scenario: "Screening student essays and written assignments before grading to flag likely AI-generated submissions for further review." },
      { role: "Hiring managers", scenario: "Checking cover letters and writing samples submitted with job applications for AI generation." },
      { role: "Content editors", scenario: "Reviewing freelance-submitted articles and blog posts to ensure they are human-written before publishing." },
    ],
    faq: [
      { q: "Can the detector identify ChatGPT, Claude, and Gemini?", a: "Yes. The detector is calibrated for output from all major AI models including ChatGPT (GPT-4), Claude, and Gemini. It uses statistical signals rather than model-specific fingerprints, so it generalizes to new AI models as well." },
      { q: "How accurate is AI text detection?", a: "Accuracy is high on clearly AI-generated content (90%+) and lower on heavily edited or humanized text. No detector is 100% accurate — use the score as one signal among several, not as definitive proof." },
      { q: "Can AI-generated text be edited to evade detection?", a: "Yes. Heavy editing, paraphrasing, and AI humanizer tools can lower detection scores. This is why detection scores should be used alongside other evidence — not as standalone proof of AI authorship." },
    ],
  },
  {
    slug: "count-words-google-doc",
    title: "How to Count Words in a Google Doc",
    metaTitle: "How to Count Words in Google Docs — And Paste Text Free",
    metaDescription: "Count words in Google Docs instantly. Use the built-in word count or paste text into a free word counter for character count, reading time, and more.",
    primaryKeyword: "count words in google doc",
    intro: "Google Docs has a built-in word counter — but it only shows total word count. For character count, reading time, sentence count, and average word length, a standalone word counter gives you more. Here's both methods.",
    toolId: "word-counter",
    toolName: "Free Word Counter",
    toolPath: "/tools/word-counter",
    steps: [
      { title: "Use Google Docs built-in word count", detail: "In Google Docs, go to Tools → Word count (or press Ctrl+Shift+C / Cmd+Shift+C on Mac). This shows total words, characters with and without spaces, and page count." },
      { title: "Enable word count display in the toolbar", detail: "Check 'Display word count while typing' in the Word count dialog to show a live counter in the bottom left of your document." },
      { title: "For more stats, copy and paste your text", detail: "Select all (Ctrl+A), copy, then paste into the free word counter tool for character count, reading time estimate, sentence count, and paragraph count." },
      { title: "Check reading time", detail: "The word counter shows estimated reading time based on 200–250 words per minute — useful for blog posts, speeches, and timed writing tasks." },
      { title: "Check character limits", detail: "For Twitter, LinkedIn, meta descriptions, or SMS limits, the character counter shows counts with and without spaces." },
    ],
    whoItsFor: [
      { role: "Writers and bloggers", scenario: "Hitting word count targets for blog posts, articles, or essays — and estimating reading time for readers." },
      { role: "Students", scenario: "Verifying essays meet assignment word count requirements before submission." },
      { role: "Content marketers", scenario: "Checking character counts for meta titles, meta descriptions, and social media captions that have strict character limits." },
    ],
    faq: [
      { q: "What is the keyboard shortcut for word count in Google Docs?", a: "Ctrl+Shift+C on Windows/Linux, Cmd+Shift+C on Mac. This opens the Word count dialog showing words, characters with spaces, and characters without spaces." },
      { q: "Does Google Docs count words in headers and footers?", a: "By default, Google Docs does not count words in headers, footers, or footnotes. The word count reflects body text only." },
      { q: "How do I count characters in Google Docs?", a: "Google Docs shows character count in the Word count dialog (Tools → Word count). For more detail — characters per paragraph, average word length, or reading time — paste your text into a standalone word counter tool." },
    ],
  },
  {
    slug: "resize-image-for-instagram",
    title: "How to Resize an Image for Instagram",
    metaTitle: "How to Resize an Image for Instagram — Free, No App Required",
    metaDescription: "Resize images to Instagram's exact dimensions — square (1080×1080), portrait (1080×1350), and landscape (1080×566) — free in your browser.",
    primaryKeyword: "resize image for instagram",
    intro: "Instagram crops images that don't match its expected aspect ratios, cutting off subjects and ruining composition. This guide shows how to resize and crop images to Instagram's exact dimensions before uploading — free, with no app required.",
    toolId: "image-resizer",
    toolName: "Free Image Resizer",
    toolPath: "/tools/image-resizer",
    steps: [
      { title: "Choose the right Instagram dimension", detail: "Instagram supports three formats: Square (1080×1080, 1:1 ratio), Portrait (1080×1350, 4:5 ratio — gets more feed space), and Landscape (1080×566, 1.91:1 ratio). Portrait gets the most screen real estate in the feed." },
      { title: "Open the image resizer", detail: "No account, no app download. The resizer runs in your browser." },
      { title: "Upload your image", detail: "Click 'Upload' or drag and drop any JPEG, PNG, or WebP image." },
      { title: "Enter the target dimensions", detail: "Type 1080 × 1080 for square, 1080 × 1350 for portrait, or 1080 × 566 for landscape. Enable 'Maintain aspect ratio' if you don't want to crop." },
      { title: "Download and upload to Instagram", detail: "Download the resized image as JPEG. Instagram accepts JPEG and PNG — JPEG is preferred as it produces smaller files at equivalent quality." },
    ],
    whoItsFor: [
      { role: "Social media managers", scenario: "Preparing batches of product, event, or brand images to exact Instagram dimensions before scheduling posts." },
      { role: "Photographers", scenario: "Cropping portfolio shots to portrait format to maximize visible image area in the Instagram feed." },
      { role: "Small business owners", scenario: "Resizing product photos for Instagram without a subscription to Canva or Adobe Express." },
    ],
    faq: [
      { q: "What is the best image size for Instagram?", a: "1080×1350 pixels (portrait, 4:5 ratio) gets the most feed space and is the recommended format for maximum engagement. Square (1080×1080) is also widely used. Landscape (1080×566) shows the smallest in the feed." },
      { q: "What happens if I upload the wrong size to Instagram?", a: "Instagram automatically crops images that don't match a supported aspect ratio, centering the crop. This can cut off important subjects. Resizing before upload gives you control over what's shown." },
      { q: "What file format should I use for Instagram?", a: "JPEG for photos — it produces the smallest file size at the best quality. PNG is accepted but results in larger uploads. Instagram re-compresses all uploaded images anyway, so starting with the right dimensions matters more than format." },
    ],
  },
  {
    slug: "convert-heic-to-jpg-iphone",
    title: "How to Convert HEIC to JPG from iPhone",
    metaTitle: "How to Convert HEIC to JPG from iPhone — Free, No App Needed",
    metaDescription: "Convert iPhone HEIC photos to JPG free online. No app download, no account. Upload and download your JPG in seconds.",
    primaryKeyword: "convert heic to jpg iphone",
    intro: "iPhones capture photos in HEIC format by default — half the file size of JPEG, but rejected by most websites, Windows PCs, and non-Apple software. This guide shows how to convert HEIC to JPG quickly and for free, without installing an app.",
    toolId: "image-converter",
    toolName: "Free Image Converter",
    toolPath: "/tools/image-converter",
    steps: [
      { title: "Export the HEIC file from your iPhone", detail: "AirDrop the photo to your Mac or PC, or use a USB cable. When AirDropping to a non-Apple device, the file usually transfers as JPEG automatically. If you still get a .heic file, proceed to the next step." },
      { title: "Check your iPhone settings for automatic conversion", detail: "On iPhone: Settings → Camera → Formats → set to 'Most Compatible' to export JPEG by default. Note this takes more storage." },
      { title: "Open the free image converter", detail: "Navigate to the image converter — no account or installation required." },
      { title: "Upload the HEIC file", detail: "Click 'Upload' or drag and drop the .heic file. The converter accepts HEIC files directly." },
      { title: "Select JPG output and download", detail: "Choose JPEG / JPG as the output format, set quality (80% recommended), then click 'Convert' and download your JPG." },
    ],
    whoItsFor: [
      { role: "iPhone users sharing photos with Windows users", scenario: "Converting HEIC photos before emailing or messaging them to contacts who use non-Apple devices." },
      { role: "Website owners and bloggers", scenario: "Converting iPhone photos to JPEG before uploading to WordPress, Squarespace, or any CMS that rejects HEIC files." },
      { role: "E-commerce sellers", scenario: "Converting product photos taken on iPhone to JPEG for upload to Shopify, Etsy, or Amazon, which typically require JPEG or PNG." },
    ],
    faq: [
      { q: "Why can't I open HEIC files on Windows?", a: "Windows does not include HEIC codec support by default. You can install the Microsoft HEIF Image Extensions from the Microsoft Store (free), or convert HEIC files to JPEG — which opens natively on every operating system." },
      { q: "How do I stop my iPhone from saving photos as HEIC?", a: "Go to Settings → Camera → Formats and select 'Most Compatible.' This saves photos as JPEG going forward. Note that HEIC uses roughly half the storage of JPEG, so switching increases storage usage." },
      { q: "Is there a quality difference when converting HEIC to JPG?", a: "At 80–85% JPEG quality, the visual difference from the original HEIC is negligible. HEIC can theoretically store more color data, but the difference is invisible in practical use." },
    ],
  },
  {
    slug: "remove-background-product-photo-amazon",
    title: "How to Remove Backgrounds from Product Photos for Amazon",
    metaTitle: "Remove Background from Product Photos for Amazon — Free Online",
    metaDescription: "Amazon requires pure white backgrounds on main product images. Remove backgrounds free in your browser — no Photoshop, no account, no watermark.",
    primaryKeyword: "remove background from product photo for amazon",
    intro: "Amazon requires all main product images to have a pure white background (#FFFFFF). This guide shows how to remove any background from product photos and replace it with white — free, in your browser, with no file size limits.",
    toolId: "remove-background-change-ai",
    toolName: "Free AI Background Remover",
    toolPath: "/tools/remove-background-change-ai",
    steps: [
      { title: "Photograph against a contrasting background", detail: "Shoot the product against grey or light blue if it is white/light colored; against white if it is dark. High contrast dramatically improves AI removal accuracy." },
      { title: "Upload to the AI background remover", detail: "Open the free AI background remover and upload your product photo. JPEG, PNG, and WebP are all supported." },
      { title: "Let the AI remove the background", detail: "The AI identifies the product and removes the background automatically in 2–5 seconds. Review the edges — check for any clipping or halos." },
      { title: "Set the background to white", detail: "Select white (#FFFFFF) as the replacement background. Amazon requires pure white, not off-white or grey." },
      { title: "Download as JPEG and check dimensions", detail: "Download the result as JPEG. Amazon requires the product to fill at least 85% of the image frame, and the minimum image size is 1000×1000px (1500×1500px recommended for zoom)." },
    ],
    whoItsFor: [
      { role: "Amazon sellers", scenario: "Preparing product main images to meet Amazon's pure white background policy for listing approval." },
      { role: "E-commerce store owners", scenario: "Creating consistent product images across a catalog — white backgrounds make products look cohesive on any page color." },
      { role: "Dropshippers", scenario: "Replacing supplier product photos (which often have busy backgrounds) with clean white-background images for their storefronts." },
    ],
    faq: [
      { q: "What background color does Amazon require for product images?", a: "Amazon requires a pure white background (#FFFFFF) for main product images. The product must fill at least 85% of the frame. Off-white, grey, or gradient backgrounds are not compliant and may result in listing suppression." },
      { q: "Can I use a free tool to remove backgrounds for Amazon listings?", a: "Yes. The AI background remover at thefreeaitools.com removes product photo backgrounds and lets you replace them with pure white — free, with no account required and no watermark on the output." },
      { q: "What image size does Amazon recommend for product photos?", a: "Amazon recommends 1500×1500 pixels minimum for zoom functionality (2000×2000px is ideal). The minimum accepted size is 1000×1000px. Use JPEG format — PNG is accepted but JPEG produces smaller files at equivalent quality." },
    ],
  },
  {
    slug: "format-json-for-api-debugging",
    title: "How to Format JSON for API Debugging",
    metaTitle: "How to Format JSON for API Debugging — Free Online JSON Formatter",
    metaDescription: "Format minified JSON API responses for readability instantly. Free browser-based JSON formatter — no signup, no upload, highlights errors.",
    primaryKeyword: "format json for api debugging",
    intro: "API responses often arrive as minified JSON — a single line of dense text that's impossible to read and debug. This guide shows how to format any JSON response for immediate readability, validate it, and find errors — free in your browser.",
    toolId: "json-formatter",
    toolName: "Free JSON Formatter",
    toolPath: "/tools/json-formatter",
    steps: [
      { title: "Copy the JSON from your API response", detail: "In browser DevTools (Network tab), Postman, curl output, or log files — copy the raw JSON response text." },
      { title: "Paste into the JSON formatter", detail: "Open the free JSON formatter and paste the raw JSON. The formatter processes it entirely in your browser — nothing is sent to any server." },
      { title: "Click Format / Beautify", detail: "The tool applies consistent 2-space indentation and line breaks, making the structure immediately readable." },
      { title: "Check for validation errors", detail: "If the JSON is malformed, the formatter highlights the error and shows the line number. Common issues: trailing commas, unquoted keys, single quotes instead of double quotes." },
      { title: "Use the tree view for deep nesting", detail: "For deeply nested JSON objects, the collapsible tree view lets you navigate to the specific key you're investigating without scrolling through the entire response." },
    ],
    whoItsFor: [
      { role: "Backend developers", scenario: "Validating API response payloads during development — checking that the response structure matches the expected schema before writing client code." },
      { role: "Frontend developers", scenario: "Inspecting API responses from third-party services to understand the data structure before writing mapping/transformation code." },
      { role: "QA engineers", scenario: "Comparing expected vs. actual JSON payloads during integration testing to identify field mismatches or unexpected data types." },
    ],
    faq: [
      { q: "Why is my JSON invalid? Common causes?", a: "The most common JSON errors are: trailing commas after the last item in an array or object (not allowed in JSON, only in JavaScript), single quotes instead of double quotes around strings, unquoted object keys, and comments (JSON doesn't support comments). The formatter error message will point to the line where the first error occurs." },
      { q: "Can the formatter handle very large JSON files?", a: "Yes. The formatter processes JSON entirely in your browser — there is no file size limit imposed by a server. Processing time depends on your device's memory; files up to several megabytes format instantly." },
      { q: "How do I minify JSON to send in an API request?", a: "The formatter also minifies JSON — removes all whitespace and line breaks, reducing payload size for API requests. This is the reverse of formatting: paste your formatted JSON and click Minify." },
    ],
  },
  {
    slug: "check-website-ssl-certificate",
    title: "How to Check a Website's SSL Certificate",
    metaTitle: "How to Check SSL Certificate — Free SSL Checker Online",
    metaDescription: "Check any website's SSL certificate expiry, issuer, and validity free online. Verify HTTPS is working before it causes a browser warning.",
    primaryKeyword: "how to check ssl certificate",
    intro: "An expired or misconfigured SSL certificate kills HTTPS, triggers browser security warnings, and destroys user trust instantly. This guide shows how to check any site's SSL certificate — expiry date, issuer, and validity — free in your browser.",
    toolId: "ssl-checker",
    toolName: "Free SSL Checker",
    toolPath: "/tools/ssl-checker",
    steps: [
      { title: "Enter the domain name", detail: "Type or paste the domain (e.g., example.com). Do not include https:// — just the domain name." },
      { title: "Click Check SSL", detail: "The tool queries the domain's SSL certificate and returns the certificate details within seconds." },
      { title: "Check the expiry date", detail: "The most important field: when the certificate expires. Certificates typically expire every 90 days (Let's Encrypt) or 1–2 years (paid certificates). Set a renewal reminder 30 days before expiry." },
      { title: "Verify the issuer and certificate chain", detail: "The issuer should be a recognized Certificate Authority (Let's Encrypt, DigiCert, Sectigo, etc.). If the issuer is unknown or the chain is incomplete, browsers will show a warning." },
      { title: "Check the Subject Alternative Names (SANs)", detail: "SANs list which domains the certificate covers. Verify your domain (and www subdomain) is included — a certificate missing a subdomain will cause errors for that subdomain." },
    ],
    whoItsFor: [
      { role: "Website owners", scenario: "Checking their own SSL certificate before it expires and causes browser warnings that drive away visitors." },
      { role: "Developers", scenario: "Verifying SSL configuration is correct after deploying a new certificate or migrating to HTTPS." },
      { role: "SEO professionals", scenario: "Checking SSL status as part of a site audit — HTTPS is a Google ranking factor and mixed content warnings affect user experience." },
    ],
    faq: [
      { q: "How do I know if a website's SSL certificate is expired?", a: "Use the free SSL checker: enter the domain and the tool will show the certificate's expiry date and current validity status. An expired certificate causes browsers to show a 'Your connection is not private' or 'NET::ERR_CERT_DATE_INVALID' error." },
      { q: "What is the difference between HTTP and HTTPS?", a: "HTTP sends data in plain text — readable by anyone on the network. HTTPS encrypts traffic using TLS (the protocol underlying SSL). HTTPS is required for any page that handles passwords, payment information, or personal data, and is a Google ranking signal." },
      { q: "How often do SSL certificates expire?", a: "Let's Encrypt certificates expire every 90 days (auto-renewed by most hosting providers). Commercial certificates typically last 1 year (398 days maximum as of 2020 browser policy). Always check your certificate's expiry and set a renewal reminder 30 days before." },
    ],
  },
]

export function getUseCase(slug: string): UseCase | undefined {
  return USE_CASES.find((u) => u.slug === slug)
}

export function getAllUseCaseSlugs(): { useCase: string }[] {
  return USE_CASES.map((u) => ({ useCase: u.slug }))
}
