import PageShell from '../_components/PageShell';
import { BreadcrumbSchema } from '../schema';
import { pageMetadata } from '@/lib/seo';
import { WHATSAPP_PHONE_DISPLAY, whatsappOrderUrl } from '@/lib/cta';

const path='/contact';
const correctionUrl=whatsappOrderUrl('Hi! I want to report a correction on the WATCHWORLDCUP IPTV website. Page URL: [add URL]. Issue: [describe]. Primary source: [add source].');
const supportUrl=whatsappOrderUrl('Hi! I need help with the WATCHWORLDCUP IPTV website or accessibility. Page/device: [add details]. Issue: [describe].');

export const metadata=pageMetadata({title:'Contact WATCHWORLDCUP',description:'Contact WATCHWORLDCUP through its published WhatsApp channel for corrections, source updates, accessibility feedback or website support.',path});

export default function Page(){return <><BreadcrumbSchema items={[{name:'Home',path:'/'},{name:'Contact',path}]}/><PageShell eyebrow="Contact" title="Reach WATCHWORLDCUP through the published channel." description={`WhatsApp ${WHATSAPP_PHONE_DISPLAY} is the currently verified public contact. Never send passwords, one-time codes, payment-card details or complete subscription credentials.`} breadcrumbs={[{label:'Home',href:'/'},{label:'Contact'}]}><div className="grid gap-5 md:grid-cols-2"><section className="glass rounded-2xl p-7"><p className="eyebrow">Editorial</p><h2 className="mt-3 text-2xl font-black">Corrections and sources</h2><p className="mt-4 text-sm leading-7 text-slate-400">Include the page URL, exact claim and a primary source where possible.</p><a href={correctionUrl} target="_blank" rel="nofollow noopener noreferrer" className="mt-6 inline-flex min-h-12 items-center rounded-full bg-red-600 px-6 py-3 font-black text-white hover:bg-red-500">Report through WhatsApp<span className="sr-only"> (opens in a new tab)</span></a></section><section className="glass rounded-2xl p-7"><p className="eyebrow">Support</p><h2 className="mt-3 text-2xl font-black">Site and accessibility help</h2><p className="mt-4 text-sm leading-7 text-slate-400">Report navigation, readability, broken-link or accessibility issues. For IPTV order questions, confirm the current service details before payment.</p><a href={supportUrl} target="_blank" rel="nofollow noopener noreferrer" className="mt-6 inline-flex min-h-12 items-center rounded-full border border-white/10 bg-white/[.055] px-6 py-3 font-black text-red-300">Contact through WhatsApp<span className="sr-only"> (opens in a new tab)</span></a></section></div><p className="mt-8 rounded-2xl border border-red-400/20 bg-red-400/[.055] p-5 text-sm leading-7 text-red-50">WhatsApp at {WHATSAPP_PHONE_DISPLAY} is the complete published contact channel for website, order, correction, privacy and accessibility requests. Keep sensitive credentials and security codes out of messages.</p></PageShell></>}
