import type { Metadata } from "next"
import Link from "next/link"
import { buildPageMetadata } from "@/lib/page-metadata"
import { Navbar } from "@/components/layout/navbar"
export const metadata: Metadata = buildPageMetadata({
  title: "Markdown to HTML: The Conversion Gotchas That Cost Me an Afternoon",
  description:
    "Markdown is almost a standard — but different parsers handle edge cases differently. Here are the specific conversion issues I ran into converting a documentation site, and how to test before deploying.",
  path: "/blog/markdown-to-html-workflow",
})

export default function Post() {
  return (
    <main className="container mx-auto max-w-3xl px-4 py-12">
      <Navbar />
      <article itemScope itemType="https://schema.org/BlogPosting">
        <meta itemProp="datePublished" content="2026-04-22" />
        <meta itemProp="dateModified" content="2026-04-22" />
        <meta itemProp="author" content="Achraf A." />

        <header className="mb-10">
          <div className="mb-4 flex flex-wrap gap-2 text-xs  text-black/60 dark:text-white/60">
            <time dateTime="2026-04-22">April 22, 2026</time>
            <span>·</span>
            <span>8 min read</span>
            <span>·</span>
            <Link href="/blog" className=" text-black/60 dark:text-white/60 underline underline-offset-2 hover:text-black">
              Blog
            </Link>
          </div>
          <h1
            className="text-3xl font-extrabold tracking-tight text-black sm:text-4xl"
            itemProp="headline"
          >
            Markdown to HTML: The Conversion Gotchas That Cost Me an Afternoon
          </h1>
          <p className="mt-4 text-lg leading-relaxed  text-black/60 dark:text-white/60">
            Markdown is almost a standard. The &quot;almost&quot; is where the problems live. Different
            parsers handle tables, nested lists, code blocks, and inline HTML differently enough
            that converting a large markdown document can surface a dozen rendering bugs you
            didn&apos;t expect.
          </p>
        </header>

        <div
          className="prose prose-neutral max-w-none prose-headings:font-bold prose-a:text-black prose-a:underline prose-a:underline-offset-[3px] hover:prose-a:opacity-60"
          itemProp="articleBody"
        >
          <h2>The conversion that started this</h2>
          <p>
            I was migrating a documentation site from a Confluence wiki to a static site generator.
            The export gave me a folder of Markdown files generated by a Confluence-to-Markdown
            tool. The static site generator used a different Markdown parser. About 15% of the pages
            had rendering issues — tables that didn&apos;t render, code blocks that merged with adjacent
            text, links that broke.
          </p>
          <p>
            I fixed them by running each file through the{" "}
            <Link href="/tools/markdown-to-html">browser-based Markdown converter</Link> to see
            the HTML output before publishing, catching issues before they went live. This is the
            list of what I found.
          </p>

          <h2>Why Markdown isn&apos;t actually a standard</h2>
          <p>
            John Gruber&apos;s original Markdown spec from 2004 left many edge cases unspecified.
            Different parsers (CommonMark, GitHub Flavored Markdown, Pandoc, MultiMarkdown,
            Python-Markdown, marked.js) have made different choices for the ambiguous cases.
            CommonMark was created in 2014 specifically to standardize the spec, and GitHub
            Flavored Markdown (GFM) extends CommonMark with tables, task lists, strikethrough,
            and autolinks.
          </p>
          <p>
            If you write Markdown for one system and render it in another, the differences in
            parser behavior will cause inconsistencies.
          </p>

          <h2>The five gotchas I ran into</h2>

          <h3>1. Tables require pipe on both ends (GFM) but not always</h3>
          <p>
            GFM tables require a pipe character at the start and end of each row:
          </p>
          <pre><code>{`| Column 1 | Column 2 |
|----------|----------|
| Cell 1   | Cell 2   |`}</code></pre>
          <p>
            Some parsers are lenient and allow tables without outer pipes. Others require the
            alignment row separator to have at least three dashes per column (<code>---</code>).
            Confluence-exported Markdown sometimes omits the leading pipe, which caused every
            table on the migrated site to render as plain text paragraphs instead of HTML tables.
            Fix: add the leading pipe to every row.
          </p>

          <h3>2. Fenced code blocks: backtick count matters</h3>
          <p>
            Code blocks delimited by triple backticks work in most parsers. But if the code inside
            the block contains triple backticks (common in documentation about Markdown itself),
            you need to use more backticks in the fence:
          </p>
          <pre><code>{`\`\`\`\`
This block contains \`\`\` inside
\`\`\`\``}</code></pre>
          <p>
            Parsers that count backtick pairs correctly handle this. Parsers that don&apos;t will close
            the code block at the first triple-backtick inside the content, causing the rest to
            render as normal text.
          </p>

          <h3>3. Nested lists require consistent indentation</h3>
          <p>
            CommonMark requires 2-space or 4-space indentation for nested list items (depending
            on the parser). Confluence exports sometimes use 3 spaces for nesting. A 3-space
            indent is valid in some parsers and not in others. The symptom: a list that looks
            correct in the original system renders as a flat, unnested list in the destination.
          </p>
          <p>
            Fix: standardize all list indentation to 2 spaces (CommonMark) or 4 spaces before
            migration. Never mix indentation levels in the same list.
          </p>

          <h3>4. Inline HTML: sanitized or passed through?</h3>
          <p>
            Markdown allows inline HTML, and most parsers pass it through to the rendered output.
            But some parsers (particularly those used in public-facing CMSes) sanitize or strip
            HTML tags for security reasons. If your Markdown contains inline{" "}
            <code>{"<div>"}</code>, <code>{"<span>"}</code>, or custom HTML elements and they
            disappear in the rendered output, the parser is sanitizing them.
          </p>
          <p>
            This is a deliberate security choice, not a bug. If you need raw HTML in your output,
            you need a parser that allows it (marked.js with <code>sanitize: false</code>, for
            example) and you need to trust your input source.
          </p>

          <h3>5. Line breaks: trailing spaces vs double newline</h3>
          <p>
            In original Markdown, a hard line break within a paragraph requires two trailing spaces
            at the end of the line. CommonMark also supports a backslash at the end of the line.
            Many editors strip trailing whitespace automatically, which silently removes hard line
            breaks from Markdown files.
          </p>
          <p>
            If your Markdown has prose that should break at specific points (addresses, poems, code
            examples written as prose) and the line breaks are disappearing in the rendered output,
            trailing spaces were stripped. The fix is to use the backslash line break (<code>\</code>
            at end of line) instead of trailing spaces, since backslashes survive editor formatting.
          </p>

          <h2>Checking output before publishing</h2>
          <p>
            The fastest way to verify Markdown renders correctly: paste it into the{" "}
            <Link href="/tools/markdown-to-html">Markdown to HTML converter</Link> and switch
            between the rendered preview and raw HTML output. The raw HTML shows you exactly
            what the parser produced, including any wrapping tags, attribute handling, and
            element nesting.
          </p>
          <p>
            For a large migration (dozens or hundreds of files), write a test script that runs
            each file through the target parser and checks for:
          </p>
          <ul>
            <li>Files where the output contains fewer HTML elements than expected (a sign
              that a list or table failed to parse)</li>
            <li>Files where <code>{"<pre>"}</code> or <code>{"<code>"}</code> tags appear in unexpected positions
              (code block boundary misalignment)</li>
            <li>Files shorter than expected (truncation from an unclosed block)</li>
          </ul>

          <h2>Markdown flavors at a glance</h2>
          <div className="overflow-x-auto my-6">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-gray-50">
                  <th className="border border-gray-200 p-3 text-left font-semibold">Flavor</th>
                  <th className="border border-gray-200 p-3 text-left font-semibold">Tables</th>
                  <th className="border border-gray-200 p-3 text-left font-semibold">Strikethrough</th>
                  <th className="border border-gray-200 p-3 text-left font-semibold">Task lists</th>
                  <th className="border border-gray-200 p-3 text-left font-semibold">Used by</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-gray-200 p-3 text-gray-600">CommonMark</td>
                  <td className="border border-gray-200 p-3 text-gray-600">No</td>
                  <td className="border border-gray-200 p-3 text-gray-600">No</td>
                  <td className="border border-gray-200 p-3 text-gray-600">No</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Base spec</td>
                </tr>
                <tr>
                  <td className="border border-gray-200 p-3 text-gray-600">GFM</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Yes</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Yes (~~text~~)</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Yes</td>
                  <td className="border border-gray-200 p-3 text-gray-600">GitHub, Gitea</td>
                </tr>
                <tr>
                  <td className="border border-gray-200 p-3 text-gray-600">MultiMarkdown</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Yes</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Yes</td>
                  <td className="border border-gray-200 p-3 text-gray-600">No</td>
                  <td className="border border-gray-200 p-3 text-gray-600">iA Writer</td>
                </tr>
                <tr>
                  <td className="border border-gray-200 p-3 text-gray-600">Pandoc MD</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Yes</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Yes</td>
                  <td className="border border-gray-200 p-3 text-gray-600">No</td>
                  <td className="border border-gray-200 p-3 text-gray-600">Pandoc</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h2>Related tools</h2>
          <ul>
            <li>
              <Link href="/tools/markdown-to-html">Markdown to HTML Converter</Link>{" "}
              — convert Markdown to HTML with live preview and raw HTML output view.
            </li>
            <li>
              <Link href="/tools/html-to-markdown">HTML to Markdown Converter</Link>{" "}
              — convert HTML back to Markdown, useful for migrating from HTML-based CMSes.
            </li>
            <li>
              <Link href="/tools/json-formatter">JSON Formatter</Link>{" "}
              — format front matter metadata (which is often JSON in some static site generators).
            </li>
          </ul>

          <hr className="my-8" />

          <p className="text-sm text-gray-400">
            Written by{" "}
            <Link href="/about" className=" text-black/60 dark:text-white/60 underline underline-offset-2 hover:text-black">
              Achraf A.
            </Link>
            , founder of TheFreeAITools — built in Morocco. The Confluence migration described
            above involved 340 pages; about 50 required manual fixes after automated conversion.
          </p>
        </div>
      </article>
    </main>
  )
}
