import { canonicalUrl, normalizePath, SITE_NAME, SITE_URL, UPDATED_ISO } from '@/lib/site';
import { catalogDatasets, DATA_LICENSE, DATA_VERSION } from '@/lib/data-catalog';

type JsonValue = Record<string, unknown>;
function JsonLd({ data }: { data: JsonValue }) { return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>; }
function socialImage(path:string){const slug=path==='/'?'home':path.replace(/^\//,'').replaceAll('/','--');return `${SITE_URL}/images/og/${slug}.webp`; }

export function OrganizationSchema() {
  return <JsonLd data={{'@context':'https://schema.org','@type':'Organization','@id':`${SITE_URL}/#organization`,name:SITE_NAME,url:SITE_URL,logo:{'@type':'ImageObject',url:`${SITE_URL}/logo.svg`,width:512,height:512},description:'WATCHWORLDCUP IPTV and M3U subscription plans, setup guidance, and independent World Cup resources.'}}/>;
}
export function IPTVServiceSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'Service','@id':`${SITE_URL}/#iptv-service`,name:'WATCHWORLDCUP IPTV / M3U Subscription Service',description:'Time-based IPTV and M3U subscription plans ordered through WhatsApp, with current content and device/app compatibility confirmed before payment.',url:SITE_URL,provider:{'@id':`${SITE_URL}/#organization`},termsOfService:`${SITE_URL}/terms-of-service`,isRelatedTo:{'@id':`${SITE_URL}/#website`}}}/>; }
export function WebSiteSchema() { return <JsonLd data={{'@context':'https://schema.org','@type':'WebSite','@id':`${SITE_URL}/#website`,url:SITE_URL,name:SITE_NAME,publisher:{'@id':`${SITE_URL}/#organization`},inLanguage:'en-US'}}/>; }
export function BreadcrumbSchema({items}:{items:Array<{name:string;path:string}>}) { return <JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:canonicalUrl(x.path)}))}}/>; }
export function ArticleSchema({headline,description,path,datePublished=UPDATED_ISO,dateModified=UPDATED_ISO}:{headline:string;description:string;path:string;datePublished?:string;dateModified?:string}) { return <JsonLd data={{'@context':'https://schema.org','@type':'Article','@id':`${SITE_URL}${path}/#article`,headline,description,image:[socialImage(path)],datePublished,dateModified,mainEntityOfPage:{'@type':'WebPage','@id':`${SITE_URL}${path}`},author:{'@type':'Organization',name:`${SITE_NAME} Editorial Team`,url:`${SITE_URL}/editorial-policy`},publisher:{'@id':`${SITE_URL}/#organization`},isAccessibleForFree:true,inLanguage:'en-US'}}/>; }
export function DatasetSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'Dataset','@id':`${SITE_URL}/research/world-cup-2026-replay-source-tracker#dataset`,name:'World Cup 2026 Authorized Replay Source Tracker',description:'A manually verified list of authorized World Cup 2026 replay and highlight source pages, including region, language, access notes, verification, and last-checked date.',url:`${SITE_URL}/research/world-cup-2026-replay-source-tracker`,creator:{'@id':`${SITE_URL}/#organization`},datePublished:'2026-08-11',dateModified:'2026-08-11',license:'https://creativecommons.org/licenses/by/4.0/',isAccessibleForFree:true,distribution:[{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:`${SITE_URL}/downloads/world-cup-2026-replay-sources.csv`},{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE_URL}/downloads/world-cup-2026-replay-sources.json`}]}}/>; }
export function FinalMatchSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'SportsEvent','@id':`${SITE_URL}/world-cup-2026/final#event`,name:'Spain vs Argentina — FIFA World Cup 2026 Final',description:'Spain defeated Argentina 1-0 after extra time in the completed FIFA World Cup 2026 final. Ferran Torres scored in the 106th minute.',url:`${SITE_URL}/world-cup-2026/final`,startDate:'2026-07-19T15:00:00-04:00',eventStatus:'https://schema.org/EventCompleted',eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',location:{'@type':'Place',name:'New York New Jersey Stadium',address:{'@type':'PostalAddress',addressLocality:'East Rutherford',addressRegion:'NJ',addressCountry:'US'}},homeTeam:{'@type':'SportsTeam',name:'Spain'},awayTeam:{'@type':'SportsTeam',name:'Argentina'},organizer:{'@type':'Organization',name:'FIFA',url:'https://www.fifa.com/'}}}/>; }
export function FinalStandingsDatasetSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'Dataset','@id':`${SITE_URL}/world-cup-2026/final-standings#dataset`,name:'FIFA World Cup 2026 Final Tournament Standings',description:'The official final placement of all 48 teams at the completed FIFA World Cup 2026, transcribed from FIFA final tournament standings.',url:`${SITE_URL}/world-cup-2026/final-standings`,creator:{'@id':`${SITE_URL}/#organization`},datePublished:'2026-08-11',dateModified:'2026-08-11',temporalCoverage:'2026-06-11/2026-07-19',spatialCoverage:['Canada','Mexico','United States'],license:'https://creativecommons.org/licenses/by/4.0/',isAccessibleForFree:true,distribution:[{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:`${SITE_URL}/downloads/world-cup-2026-final-standings.csv`},{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE_URL}/downloads/world-cup-2026-final-standings.json`}]}}/>; }
export function WorldCupWinnersDatasetSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'Dataset','@id':`${SITE_URL}/world-cup-history/winners#dataset`,name:'FIFA World Cup Champions and Final Results, 1930–2026',description:'A source-linked transcription of all 23 completed men’s FIFA World Cup editions, including host, champion, runner-up, deciding score, and decision method.',url:`${SITE_URL}/world-cup-history/winners`,creator:{'@id':`${SITE_URL}/#organization`},datePublished:'2026-08-11',dateModified:'2026-08-11',temporalCoverage:'1930/2026',license:'https://creativecommons.org/licenses/by/4.0/',isAccessibleForFree:true,isBasedOn:['https://www.fifa.com/en/tournaments/mens/worldcup/articles/world-cup-champions-1930-1978-uruguay-italy-germany-brazil-england-argentina','https://www.fifa.com/en/tournaments/mens/worldcup/articles/world-cup-champions-1982-2026-italy-argentina-germany-brazil-france-spain'],distribution:[{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:`${SITE_URL}/downloads/world-cup-winners-1930-2026.csv`},{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE_URL}/downloads/world-cup-winners-1930-2026.json`}]}}/>; }
export function WorldCupTitleRecordsDatasetSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'Dataset','@id':`${SITE_URL}/world-cup-history/records#dataset`,name:'World Cup Title and Final Appearance Records',description:'Derived championship, runner-up and final-appearance totals for the 13 teams to reach a men’s World Cup deciding match or the 1950 final-round decider.',url:`${SITE_URL}/world-cup-history/records`,creator:{'@id':`${SITE_URL}/#organization`},datePublished:DATA_VERSION,dateModified:DATA_VERSION,temporalCoverage:'1930/2026',license:DATA_LICENSE,isAccessibleForFree:true,isBasedOn:`${SITE_URL}/world-cup-history/winners`,distribution:[{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:`${SITE_URL}/downloads/world-cup-title-records.csv`},{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE_URL}/downloads/world-cup-title-records.json`}]}}/>; }
export function DataCatalogSchema(){return <JsonLd data={{'@context':'https://schema.org','@type':'DataCatalog','@id':`${SITE_URL}/data#catalog`,name:'WATCHWORLDCUP Open Data Catalog',description:'Open, source-linked World Cup archive and replay-source datasets with CSV and JSON distributions, field definitions, licenses, versions, and checksums.',url:`${SITE_URL}/data`,publisher:{'@id':`${SITE_URL}/#organization`},datePublished:DATA_VERSION,dateModified:DATA_VERSION,license:DATA_LICENSE,dataset:catalogDatasets.map(item=>({'@type':'Dataset','@id':`${SITE_URL}${item.page}#dataset`,name:item.title,url:`${SITE_URL}${item.page}`,distribution:[{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:`${SITE_URL}${item.csv}`},{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE_URL}${item.json}`}]}))}}/>; }
export function CompletedTournamentSchema() { return <JsonLd data={{'@context':'https://schema.org','@type':'SportsEvent','@id':`${SITE_URL}/world-cup-2026/#event`,name:'FIFA World Cup 2026',description:'The completed 48-team tournament held across Canada, Mexico and the United States from June 11 to July 19, 2026.',url:`${SITE_URL}/world-cup-2026`,startDate:'2026-06-11',endDate:'2026-07-19',eventStatus:'https://schema.org/EventCompleted',eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',location:[{'@type':'Country',name:'Canada'},{'@type':'Country',name:'Mexico'},{'@type':'Country',name:'United States'}],organizer:{'@type':'Organization',name:'FIFA',url:'https://www.fifa.com/'}}}/>; }
export function FAQSchema({faqs,path}:{faqs:Array<{question:string;answer:string}>;path:string}) { return <JsonLd data={{'@context':'https://schema.org','@type':'FAQPage','@id':`${canonicalUrl(normalizePath(path))}#faq`,mainEntity:faqs.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))}}/>; }
