import PageShell from '../_components/PageShell';
import { BreadcrumbSchema } from '../schema';
import { pageMetadata } from '@/lib/seo';
import { whatsappOrderUrl } from '@/lib/cta';
import { CheckCircleIcon } from '../_components/Icons';

const path='/corrections';
const correctionUrl=whatsappOrderUrl('Hi! I want to report a correction on the WATCHWORLDCUP IPTV website. Page URL: [add URL]. Disputed passage: [quote]. Evidence or primary source: [add source].');

export const metadata=pageMetadata({title:'Corrections Policy',description:'How to report factual errors, broken sources, rights changes, accessibility problems, or material updates to WATCHWORLDCUP.',path});

export default function Page(){return <><BreadcrumbSchema items={[{name:'Home',path:'/'},{name:'Corrections',path}]}/><PageShell eyebrow="Accountability" title="Report an error or material change." description="Send the URL, disputed passage and a primary source where possible. We review factual errors, broken sources, rights changes, device changes and accessibility problems." breadcrumbs={[{label:'Home',href:'/'},{label:'Corrections'}]}><div className="grid gap-5 md:grid-cols-2"><section className="glass rounded-2xl p-7"><h2 className="text-2xl font-black">What to include</h2><ul className="mt-5 space-y-3 text-sm leading-7 text-slate-300">{['Page URL','Exact sentence or table row','Why it may be wrong','Primary source or reproducible evidence','Whether the issue affects user safety or payment decisions'].map(x=><li key={x} className="flex gap-3"><CheckCircleIcon className="mt-1 h-5 w-5 shrink-0 text-red-400"/>{x}</li>)}</ul></section><section className="glass rounded-2xl p-7"><h2 className="text-2xl font-black">Published contact channel</h2><p className="mt-4 text-sm leading-7 text-slate-400">Use the existing WATCHWORLDCUP WhatsApp destination. Do not send passwords, payment-card details, private account credentials or one-time codes.</p><a href={correctionUrl} target="_blank" rel="nofollow noopener noreferrer" className="mt-6 inline-flex min-h-12 items-center rounded-full bg-red-600 px-6 py-3 font-black text-white hover:bg-red-500">Report correction on WhatsApp<span className="sr-only"> (opens in a new tab)</span></a></section></div><section className="mt-12 rounded-2xl border border-white/10 bg-white/[.035] p-7"><h2 className="text-2xl font-black">Material corrections log</h2><p className="mt-4 text-sm leading-7 text-slate-400">No material corrections have been recorded since this rebuild was prepared on 11 August 2026. Published corrections will appear here with the date, page, issue and resolution.</p></section></PageShell></>}
