export const DATA_VERSION='2026-08-11';
export const DATA_LICENSE='https://creativecommons.org/licenses/by/4.0/';
export type CatalogDataset={id:string;title:string;description:string;page:string;rows:number;csv:string;json:string;updated:string;fields:Array<{name:string;description:string}>};
export const catalogDatasets:CatalogDataset[]=[
{id:'replay-sources-2026',title:'World Cup 2026 Replay Source Tracker',description:'Manually checked authorized replay and highlight source observations with region, language, access, verification and dates.',page:'/research/world-cup-2026-replay-source-tracker',rows:4,csv:'/downloads/world-cup-2026-replay-sources.csv',json:'/downloads/world-cup-2026-replay-sources.json',updated:DATA_VERSION,fields:[{name:'platform',description:'Authorized platform or service observed.'},{name:'region',description:'Market scope associated with the observation.'},{name:'language',description:'Observed or documented commentary language.'},{name:'content',description:'Replay or highlight content described by the source page.'},{name:'access',description:'Known payment, account, device or region condition.'},{name:'verification',description:'What was directly observed and what remains limited.'},{name:'url',description:'Official or authorized source URL.'},{name:'last_checked',description:'ISO date of the observation.'}]},
{id:'final-standings-2026',title:'World Cup 2026 Final Standings',description:'FIFA’s final placement of all 48 teams, including the tied seventh-place record and finish stage.',page:'/world-cup-2026/final-standings',rows:48,csv:'/downloads/world-cup-2026-final-standings.csv',json:'/downloads/world-cup-2026-final-standings.json',updated:DATA_VERSION,fields:[{name:'rank',description:'FIFA final rank; 7= preserves the published tie.'},{name:'team',description:'Team name used in the final standings.'},{name:'finish',description:'Champion, placement match, or elimination stage.'},{name:'source_url',description:'FIFA source article.'},{name:'source_published',description:'Source publication date.'},{name:'last_checked',description:'ISO date the transcription was checked.'}]},
{id:'world-cup-winners-history',title:'World Cup Winners, 1930–2026',description:'All 23 completed men’s World Cup editions with host, champion, runner-up, deciding result and decision method.',page:'/world-cup-history/winners',rows:23,csv:'/downloads/world-cup-winners-1930-2026.csv',json:'/downloads/world-cup-winners-1930-2026.json',updated:DATA_VERSION,fields:[{name:'year',description:'Tournament edition year.'},{name:'host',description:'Host country or countries.'},{name:'champion',description:'Edition champion using the historical team name.'},{name:'runner_up',description:'Second-placed team or decisive final-round opponent.'},{name:'result',description:'Deciding score and shootout score where applicable.'},{name:'decision',description:'Regulation, extra time, shootout, or final-round decider.'},{name:'source_url',description:'FIFA source article.'},{name:'last_checked',description:'ISO date the transcription was checked.'}]},
{id:'world-cup-title-records',title:'World Cup Title and Final Appearance Records',description:'Derived title, runner-up and final-appearance totals for every team to reach a men’s World Cup deciding match or 1950 decider.',page:'/world-cup-history/records',rows:13,csv:'/downloads/world-cup-title-records.csv',json:'/downloads/world-cup-title-records.json',updated:DATA_VERSION,fields:[{name:'team',description:'Finalist team with West Germany normalized to Germany for aggregate records.'},{name:'titles',description:'Number of World Cup championships.'},{name:'runner_up_finishes',description:'Number of second-place finishes.'},{name:'final_appearances',description:'Titles plus runner-up finishes.'},{name:'years_won',description:'Pipe-separated championship years.'},{name:'years_runner_up',description:'Pipe-separated runner-up years.'},{name:'source_dataset',description:'Visible edition-level source dataset.'},{name:'last_checked',description:'ISO date the derived record was checked.'}]}
];
