const expansionToolIdList = [
  "accessibility-focus-order-visualizer",
  "alt-text-length-checker",
  "aspect-ratio-layout-calculator",
  "aria-label-reviewer",
  "base64-file-encoder",
  "beat-interval-calculator",
  "bpm-delay-time-calculator",
  "break-even-calculator",
  "capacitor-charge-discharge-calculator",
  "coin-flip-simulator",
  "color-contrast-checker",
  "css-grid-template-generator",
  "csv-column-profiler",
  "data-size-estimator",
  "escape-velocity-calculator",
  "exif-gps-remover",
  "filename-sanitizer",
  "flashcard-randomizer",
  "focusable-elements-checker",
  "fraction-simplifier-calculator",
  "frequency-to-note-converter",
  "har-file-viewer-api-timeline",
  "heading-structure-outline",
  "internal-link-graph-visualizer",
  "invoice-late-fee-calculator",
  "json-path-finder",
  "json-schema-builder-validator",
  "led-series-resistor-calculator",
  "line-ending-converter",
  "meta-description-length-checker",
  "moon-phase-finder",
  "ohms-law-power-triangle-calculator",
  "password-strength-checker",
  "pdf-metadata-privacy-checker",
  "planet-weight-calculator",
  "power-supply-runtime-calculator",
  "pricing-markup-calculator",
  "profit-margin-calculator",
  "query-string-parser",
  "redirect-chain-mapper",
  "regex-escape-helper",
  "resistor-color-code-calculator",
  "sales-tax-calculator",
  "saas-pricing-margin-calculator",
  "scientific-notation-converter",
  "schema-markup-builder-validator",
  "serp-snippet-preview",
  "sitemap-priority-planner",
  "slug-optimizer",
  "spacing-scale-generator",
  "study-session-planner",
  "subscription-revenue-forecast",
  "svg-sprite-sheet-generator",
  "telescope-field-of-view-calculator",
  "telescope-magnification-comparator",
  "unit-circle-visualizer",
  "utm-builder-validator",
  "voltage-divider-calculator",
] as const

export const expansionToolIds = new Set<string>(expansionToolIdList)

export function isExpansionToolId(toolId: string) {
  return expansionToolIds.has(toolId)
}
