import { ArrowRightIcon } from '../_components/Icons';
import PageShell from '../_components/PageShell';
import { BreadcrumbSchema } from '../schema';
import { pageMetadata } from '@/lib/seo';
const path='/updates';
export const metadata=pageMetadata({title:'Site & Dataset Updates — WATCHWORLDCUP Changelog',description:'Dated changes to WATCHWORLDCUP sources, datasets, editorial coverage, technical quality, and correction status.',path});
const updates=[
  {date:'2026-08-11',title:'Premium 2026 streaming design system refined',text:'Upgraded navigation, hero hierarchy, glass surfaces, card depth, buttons, pricing, order controls, typography, spacing, responsive behavior and motion while preserving routes, claims, data, ordering and SEO functionality.'},
  {date:'2026-08-11',title:'Guided WhatsApp order preparation launched',text:'Added a private-by-design order page with plan selection, optional country/device/app details, branded plan-specific WhatsApp messages, order-intent events, and explicit pre-payment confirmation steps.'},
  {date:'2026-08-11',title:'Public WATCHWORLDCUP IPTV service architecture launched',text:'Repositioned the primary experience around owner-authorized IPTV/M3U subscriptions, three verified plan prices and WhatsApp ordering, with separate Live TV, Sports, Movies, Series, Pricing and Setup pages using neutral categories and pre-purchase verification instead of fabricated inventory.'},
  {date:'2026-08-11',title:'Commercial IPTV release gated pending documentation',text:'Disabled public sales CTAs by default and kept pricing, catalog, checkout, and proposed commercial routes out of navigation and search until operator, licensing, inventory, fulfillment, refund, support, privacy, and payment evidence is verified.'},
  {date:'2026-08-11',title:'World Cup title and final-appearance records published',text:'Added a derived 13-team records table covering titles, runner-up finishes, final appearances, retained championships, host champions, deciding methods, and matching CSV/JSON distributions.'},
  {date:'2026-08-11',title:'External WhatsApp CTA and measurement framework added',text:'Added a site-wide bottom-right WhatsApp button, a disclosed footer conversion panel, sponsored/nofollow attributes, local CTA event taxonomy, privacy and terms disclosures, ROI formulas, and automated commercial-link checks.'},
  {date:'2026-08-11',title:'Open data catalog, JSON distributions, and checksums released',text:'Published a crawlable DataCatalog with field definitions, versions, provenance, CSV and JSON downloads, SHA-256 integrity hashes, and automated parity checks across three datasets.'},
  {date:'2026-08-11',title:'Evergreen World Cup history and winners dataset added',text:'Published a source-linked history hub and a 23-edition winners dataset covering hosts, champions, runners-up, deciding results, title records, the 1950 final-round distinction, and an open CSV.'},
  {date:'2026-08-11',title:'Unique metadata images generated for every indexable page',text:'Added 29 first-party 1200×630 Open Graph and Twitter cards, image sitemap entries, descriptive image metadata, automated dimension and delivery checks, and a generated-imagery disclosure.'},
  {date:'2026-08-11',title:'Final, awards, and 48-team standings published',text:'Added source-backed archives for Spain’s extra-time final victory, FIFA’s principal award winners and Golden Boot top ten, and the official final placement of all 48 teams with an open CSV transcription.'},
  {date:'2026-08-11',title:'Replay source dataset published',text:'Published four manually checked observations covering FOX, two Tubi full-match pages, and a Peacock region-verification limitation. Added a downloadable CSV, source links, methodology, limitations, and correction route.'},
  {date:'2026-08-11',title:'Completed-tournament archive update',text:'Updated the archive to record Spain as champion on July 19, 2026 and replaced pre-event language with a completed-tournament archive model.'},
  {date:'2026-08-11',title:'Open research and measurement methods added',text:'Published a reproducible streaming benchmark protocol, measurement template, latency explainer, accessibility checklist, legal cable-free guide, RSS feed, and security contact.'},
  {date:'2026-08-11',title:'SEO recovery foundation completed in the rebuild',text:'Rebuilt the site around server-rendered editorial content, intentional crawl controls, one-hop legacy redirects, a real 404, a retired-checkout 410, defensible schema, and source-linked trust pages.'}
];
export default function Page(){return <><BreadcrumbSchema items={[{name:'Home',path:'/'},{name:'Updates',path}]}/><PageShell eyebrow="Public change record" title="Site and dataset updates." description="A dated record of material editorial, source, dataset, and technical changes. Minor copy edits may not appear here." breadcrumbs={[{label:'Home',href:'/'},{label:'Updates'}]}><ol className="relative border-l border-white/10 pl-7">{updates.map(item=><li key={`${item.date}-${item.title}`} className="mb-10 last:mb-0"><span className="absolute -left-1.5 mt-2 h-3 w-3 rounded-full bg-red-400"/><time dateTime={item.date} className="eyebrow">{new Date(`${item.date}T12:00:00Z`).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'})}</time><h2 className="mt-3 text-2xl font-black">{item.title}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">{item.text}</p></li>)}</ol><section className="mt-14 rounded-2xl border border-white/10 bg-white/[.035] p-7"><h2 className="text-2xl font-black">Corrections and verification</h2><p className="mt-4 text-sm leading-7 text-slate-300">Material factual corrections are labeled on the affected page and recorded through the corrections policy. Replay-source observations are snapshots, not guarantees; region, account state, language, and expiry can change independently.</p><a href="/corrections" className="mt-5 inline-block font-black text-red-400">Read the corrections policy<ArrowRightIcon className="ml-2 inline h-4 w-4"/></a></section></PageShell></>}
