"use client"

import React, { useState, useId } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ToolLayout, ToolCard } from "@/components/layout/tool-layout"
import { useClipboard } from "@/hooks/use-clipboard"
import { 
  Copy, Download, Plus, Trash2, Bot, Check, 
  CheckCircle2, Zap, Shield, HelpCircle, Link2, 
  FileText, Globe 
} from "lucide-react"

interface Rule {
  id: string
  type: "allow" | "disallow"
  path: string
}

export default function RobotsTxtPage() {
  const [userAgent, setUserAgent] = useState("*")
  const [rules, setRules] = useState<Rule[]>([
    { id: "1", type: "allow", path: "/" },
    { id: "2", type: "disallow", path: "/admin/" },
  ])
  const [sitemap, setSitemap] = useState("")
  const [crawlDelay, setCrawlDelay] = useState("")
  const [copied, setCopied] = useState(false)
  
  const { copy } = useClipboard()
  const id = useId()

  const addRule = () => {
    setRules([...rules, { id: Math.random().toString(36).substr(2, 9), type: "disallow", path: "" }])
  }

  const removeRule = (idToRemove: string) => {
    setRules(rules.filter((rule) => rule.id !== idToRemove))
  }

  const updateRule = (idToUpdate: string, field: keyof Omit<Rule, "id">, value: string) => {
    setRules(rules.map(rule => 
      rule.id === idToUpdate ? { ...rule, [field]: value } : rule
    ))
  }

  const generateRobotsTxt = () => {
    let output = `# Generated by Toolkit\n`
    output += `User-agent: ${userAgent || "*"}\n`
    
    if (crawlDelay.trim()) {
      output += `Crawl-delay: ${crawlDelay.trim()}\n`
    }
    
    rules.forEach((rule) => {
      if (rule.path.trim()) {
        const type = rule.type === "allow" ? "Allow" : "Disallow"
        output += `${type}: ${rule.path.trim()}\n`
      }
    })
    
    if (sitemap.trim()) {
      output += `\nSitemap: ${sitemap.trim()}\n`
    }
    
    return output
  }

  const generatedCode = generateRobotsTxt()

  const handleCopy = async () => {
    if (!generatedCode) return
    await copy(generatedCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const download = () => {
    const blob = new Blob([generatedCode], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = "robots.txt"
    link.click()
    URL.revokeObjectURL(url)
  }

  // JSON-LD Schema for rich search results
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What is a robots.txt file?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "A robots.txt file is a simple text file placed in the root directory of your website. It uses the Robots Exclusion Protocol to tell web crawlers and search engine bots (like Googlebot) which pages or files they are allowed or forbidden to request from your site."
        }
      },
      {
        "@type": "Question",
        "name": "Does robots.txt hide my pages from Google?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes and no. A 'Disallow' directive prevents Google from crawling the page, but the URL might still appear in search results if other sites link to it. To completely hide a page from search results, you should use the 'noindex' meta tag instead."
        }
      },
      {
        "@type": "Question",
        "name": "Where do I put the robots.txt file?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The file must be named exactly 'robots.txt' and must be uploaded to the root directory of your website (e.g., https://www.yourdomain.com/robots.txt). Search engines will not look for it in subdirectories."
        }
      },
      {
        "@type": "Question",
        "name": "What does User-agent: * mean?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The asterisk (*) is a wildcard that applies the following rules to all web crawlers. If you want to target a specific bot, you would replace the asterisk with the bot's specific user-agent name (e.g., 'Googlebot' or 'Bingbot')."
        }
      }
    ]
  }

  const toolSchema = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "name": "Free Robots.txt Generator",
    "applicationCategory": "DeveloperApplication",
    "operatingSystem": "All",
    "description": "Generate optimized robots.txt files for your website instantly to control search engine crawlers and improve SEO."
  }

  return (
    <>
      {/* Inject SEO Schemas */}

      <div className="flex flex-col gap-10 max-w-6xl mx-auto w-full">
        
        {/* Header Section */}
        <header className="text-center space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary font-medium text-sm mb-2">
            <Bot className="h-4 w-4" aria-hidden="true" /> SEO Utility
          </div>
          <h2 className="text-4xl font-extrabold tracking-tight lg:text-5xl text-foreground">
            Free Robots.txt Generator
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Instantly generate perfectly formatted robots.txt files to manage web crawlers, protect sensitive directories, and optimize your website's crawl budget.
          </p>
        </header>

        {/* Interactive Tool Section */}
        <section aria-label="Robots.txt Generator Configuration" className="grid gap-6 lg:grid-cols-2 items-start">
          
          {/* Configuration Panel */}
          <div className="space-y-6">
            <ToolCard title="1. Global Settings">
              <div className="space-y-5">
                <div className="space-y-2">
                  <Label htmlFor={`${id}-user-agent`} className="font-semibold">User Agent</Label>
                  <Input
                    id={`${id}-user-agent`}
                    placeholder="* (Applies to all bots)"
                    value={userAgent}
                    onChange={(e) => setUserAgent(e.target.value)}
                    aria-label="Target User Agent"
                  />
                  <p className="text-xs text-muted-foreground">
                    Use <code className="bg-muted px-1 py-0.5 rounded">*</code> for all bots, or specify a bot like <code className="bg-muted px-1 py-0.5 rounded">Googlebot</code>.
                  </p>
                </div>

                <div className="space-y-2">
                  <Label htmlFor={`${id}-sitemap`} className="font-semibold">Sitemap URL <span className="text-muted-foreground font-normal">(Optional)</span></Label>
                  <Input
                    id={`${id}-sitemap`}
                    type="url"
                    placeholder="https://example.com/sitemap.xml"
                    value={sitemap}
                    onChange={(e) => setSitemap(e.target.value)}
                    aria-label="Sitemap URL"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor={`${id}-crawl-delay`} className="font-semibold">Crawl Delay <span className="text-muted-foreground font-normal">(Optional)</span></Label>
                  <Input
                    id={`${id}-crawl-delay`}
                    type="number"
                    min="1"
                    placeholder="e.g., 10"
                    value={crawlDelay}
                    onChange={(e) => setCrawlDelay(e.target.value)}
                    aria-label="Crawl Delay in seconds"
                  />
                  <p className="text-xs text-muted-foreground">
                    Seconds to wait between requests (Note: Googlebot largely ignores this).
                  </p>
                </div>
              </div>
            </ToolCard>

            <ToolCard title="2. Access Rules">
              <div className="space-y-4">
                <div className="space-y-3">
                  {rules.map((rule, index) => (
                    <div key={rule.id} className="flex items-start gap-2 animate-in fade-in slide-in-from-top-2 duration-300">
                      <div className="w-[120px] shrink-0">
                        <Select
                          value={rule.type}
                          onValueChange={(value: "allow" | "disallow") => updateRule(rule.id, "type", value)}
                          aria-label={`Rule type ${index + 1}`}
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="allow" className="text-green-600 font-medium">Allow</SelectItem>
                            <SelectItem value="disallow" className="text-red-600 font-medium">Disallow</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="flex-grow">
                        <Input
                          placeholder="/path/to/directory/"
                          value={rule.path}
                          onChange={(e) => updateRule(rule.id, "path", e.target.value)}
                          aria-label={`Rule path ${index + 1}`}
                        />
                      </div>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => removeRule(rule.id)}
                        className="shrink-0 text-muted-foreground hover:text-destructive hover:bg-destructive/10"
                        aria-label={`Remove rule ${index + 1}`}
                        title="Remove rule"
                      >
                        <Trash2 className="h-4 w-4" aria-hidden="true" />
                      </Button>
                    </div>
                  ))}
                </div>

                <Button 
                  variant="secondary" 
                  onClick={addRule} 
                  className="w-full gap-2 border border-dashed"
                  aria-label="Add new rule"
                >
                  <Plus className="h-4 w-4" aria-hidden="true" /> Add Rule
                </Button>
              </div>
            </ToolCard>
          </div>

          {/* Output Panel */}
          <div className="lg:sticky lg:top-6">
            <ToolCard title="3. Generated File">
              <div className="space-y-4 flex flex-col h-full">
                <div className="relative">
                  <Label htmlFor={`${id}-output`} className="sr-only">Generated robots.txt Output</Label>
                  <Textarea
                    id={`${id}-output`}
                    value={generatedCode}
                    readOnly
                    placeholder="Your generated file content will appear here..."
                    className="min-h-[400px] font-mono text-sm bg-muted/20 border-dashed focus-visible:ring-1 resize-y whitespace-pre"
                    spellCheck={false}
                  />
                </div>

                <div className="block gap-3 pt-2">
                  <Button 
                    onClick={handleCopy} 
                    className="w-full gap-2 font-medium"
                    aria-label="Copy generated robots.txt to clipboard"
                  >
                    {copied ? (
                      <>
                        <Check className="h-4 w-4 text-green-500" aria-hidden="true" />
                        <span className="text-green-500">Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="h-4 w-4" aria-hidden="true" />
                        Copy File
                      </>
                    )}
                  </Button>
                  <Button 
                    variant="outline" 
                    onClick={download} 
                    className="w-full gap-2 font-medium bg-background"
                    aria-label="Download robots.txt file"
                  >
                    <Download className="h-4 w-4" aria-hidden="true" />
                    Download .txt
                  </Button>
                </div>
              </div>
            </ToolCard>
          </div>
        </section>

      </div>
    </>
  )
}