import { ArrowRightIcon } from '../_components/Icons';
import Link from 'next/link';
import PageShell from '../_components/PageShell';
import { BreadcrumbSchema } from '../schema';
import { guides } from '@/lib/guides';
import { pageMetadata } from '@/lib/seo';
const path='/guides';
export const metadata=pageMetadata({title:'Live Sports Streaming Guides | WATCHWORLDCUP',description:'Evidence-led guides on 4K sports streaming, internet speed requirements, buffering diagnosis, device selection, and IPTV legal basics. Updated with original measurements and sources.',path});
export default function Page(){return <><BreadcrumbSchema items={[{name:'Home',path:'/'},{name:'Guides',path}]}/><PageShell eyebrow="Streaming knowledge center" title="Practical sports-streaming guides with sources and limits." description="No anti-freeze magic or anonymous APK shortcuts. These guides explain the device, network, codec, HDMI, and rights questions that determine the real experience." breadcrumbs={[{label:'Home',href:'/'},{label:'Guides'}]}><div className="grid gap-5 md:grid-cols-2">{guides.map(g=><article key={g.slug} className="glass rounded-2xl p-7"><div className="flex justify-between gap-4 text-xs font-black uppercase tracking-[.16em] text-red-400"><span>{g.category}</span><span className="text-slate-400">{g.readingTime}</span></div><h2 className="mt-5 text-2xl font-black"><Link href={`/guides/${g.slug}`} className="hover:text-red-300">{g.title}</Link></h2><p className="mt-4 text-sm leading-7 text-slate-400">{g.description}</p><Link href={`/guides/${g.slug}`} className="mt-6 inline-block font-black text-red-400">Read the guide<ArrowRightIcon className="ml-2 inline h-4 w-4"/></Link></article>)}{[
{href:'/guides/watch-soccer-without-cable',tag:'Authorized viewing',title:'Watch soccer without cable legally',text:'Compare antenna, direct app, licensed bundle, league service and replay paths.'},
{href:'/guides/streaming-latency',tag:'Technical',title:'Sports streaming delay explained',text:'Understand encoding, HLS segments, CDN delivery, player buffers and spoilers.'},
{href:'/guides/sports-streaming-accessibility',tag:'Accessibility',title:'Sports accessibility checklist',text:'Check captions, audio, controls, contrast, support and replay parity.'}
].map(x=><article key={x.href} className="glass rounded-2xl p-7"><p className="eyebrow">{x.tag}</p><h2 className="mt-5 text-2xl font-black"><Link href={x.href}>{x.title}</Link></h2><p className="mt-4 text-sm leading-7 text-slate-400">{x.text}</p><Link href={x.href} className="mt-6 inline-block font-black text-red-400">Read guide<ArrowRightIcon className="ml-2 inline h-4 w-4"/></Link></article>)}<article className="rounded-2xl border border-red-400/20 bg-red-400/[.055] p-7"><p className="eyebrow !text-red-300">Buyer safety</p><h2 className="mt-5 text-2xl font-black"><Link href="/guides/is-iptv-legal">Is IPTV legal?</Link></h2><p className="mt-4 text-sm leading-7 text-slate-300">The protocol is technology. Legality depends on content rights, licensing, and how access is sold.</p><Link href="/guides/is-iptv-legal" className="mt-6 inline-block font-black text-red-300">Read the legal-technology explainer<ArrowRightIcon className="ml-2 inline h-4 w-4"/></Link></article></div></PageShell></>}
