"use client"

import React, { useId, useState, useEffect, useRef, useCallback } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { ToolCard } from "@/components/layout/tool-layout"
import { useClipboard } from "@/hooks/use-clipboard"
import {
  Copy, Check, AlertCircle, Shield, Loader2,
  Sparkles, BarChart2, RefreshCw, ChevronDown, ChevronUp,
  Clock, FileText, Zap, Brain, AlertTriangle, FileSearch, Wand2
} from "lucide-react"
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  BarElement,
  RadialLinearScale,
  PointElement,
  LineElement,
  Filler,
} from "chart.js"
import { Doughnut, Bar, Radar } from "react-chartjs-2"

ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  BarElement,
  RadialLinearScale,
  PointElement,
  LineElement,
  Filler
)

// ─── Rate Limit: 3 tries per 3 hours per browser ──────────────────────────────
const RATE_LIMIT_KEY = "aitd_usage"
const RATE_LIMIT_MAX = 3
const RATE_LIMIT_WINDOW = 3 * 60 * 60 * 1000 // 3 hours in ms

function getRateLimit(): { count: number; windowStart: number } {
  try {
    const raw = localStorage.getItem(RATE_LIMIT_KEY)
    if (!raw) return { count: 0, windowStart: Date.now() }
    return JSON.parse(raw)
  } catch {
    return { count: 0, windowStart: Date.now() }
  }
}

function incrementRateLimit() {
  const now = Date.now()
  const data = getRateLimit()
  const inWindow = now - data.windowStart < RATE_LIMIT_WINDOW
  const next = inWindow
    ? { count: data.count + 1, windowStart: data.windowStart }
    : { count: 1, windowStart: now }
  localStorage.setItem(RATE_LIMIT_KEY, JSON.stringify(next))
}

function getRemainingTries(): number {
  const now = Date.now()
  const data = getRateLimit()
  if (now - data.windowStart >= RATE_LIMIT_WINDOW) return RATE_LIMIT_MAX
  return Math.max(0, RATE_LIMIT_MAX - data.count)
}

function getResetMinutes(): number {
  const data = getRateLimit()
  const elapsed = Date.now() - data.windowStart
  return Math.ceil((RATE_LIMIT_WINDOW - elapsed) / 60000)
}

// ─── Score Parser ────────────────────────────────────────────────────────────
interface ParsedResult {
  aiPercent: number
  humanPercent: number
  perplexity: number
  burstiness: number
  repetition: number
  explanation: string
  verdict: "ai" | "human" | "mixed"
}

function parseResult(raw: string): ParsedResult {
  const lower = raw.toLowerCase()

  const match =
    raw.match(/(\d{1,3})\s*%\s*(ai|artificial)/i) ||
    raw.match(/(ai[- ]generated|generated by ai)[^\d]*(\d{1,3})\s*%/i) ||
    raw.match(/(\d{1,3})\s*%\s*(chance|probability|likelihood)/i) ||
    raw.match(/(\d{1,3})\s*percent/i)

  let aiPercent = 50
  if (match) {
    const num = parseInt(match[1] || match[2], 10)
    if (!isNaN(num) && num >= 0 && num <= 100) aiPercent = num
  } else if (lower.includes("likely ai") || lower.includes("almost certainly ai") || lower.includes("highly likely ai")) {
    aiPercent = 88
  } else if (lower.includes("likely human") || lower.includes("almost certainly human")) {
    aiPercent = 12
  } else if (lower.includes("mixed") || lower.includes("partially")) {
    aiPercent = 52
  }

  const hasRepetition = lower.includes("repetit") || lower.includes("redundan") || lower.includes("repeat")
  const hasBurstiness = lower.includes("varied") || lower.includes("varied sentence") || lower.includes("natural flow")
  const highPerplexity = lower.includes("perplexity") || lower.includes("unpredictable") || lower.includes("creative")

  const perplexity = highPerplexity ? Math.max(30, 100 - aiPercent + Math.random() * 10) : Math.min(80, aiPercent * 0.6 + Math.random() * 15)
  const burstiness = hasBurstiness ? Math.max(35, 100 - aiPercent + Math.random() * 12) : Math.min(75, aiPercent * 0.55 + Math.random() * 10)
  const repetition = hasRepetition ? Math.min(90, aiPercent * 0.8 + Math.random() * 10) : Math.max(10, aiPercent * 0.4 + Math.random() * 15)

  const verdict: "ai" | "human" | "mixed" = aiPercent >= 70 ? "ai" : aiPercent <= 35 ? "human" : "mixed"

  return {
    aiPercent,
    humanPercent: 100 - aiPercent,
    perplexity: Math.round(perplexity),
    burstiness: Math.round(burstiness),
    repetition: Math.round(repetition),
    explanation: raw,
    verdict,
  }
}

// ─── Word Stats ──────────────────────────────────────────────────────────────
function getTextStats(text: string) {
  const words = text.trim().split(/\s+/).filter(Boolean)
  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0)
  const avgWordsPerSentence = sentences.length ? Math.round(words.length / sentences.length) : 0
  return { words: words.length, sentences: sentences.length, avgWordsPerSentence }
}

// ─── Verdict Badge ───────────────────────────────────────────────────────────
function VerdictBadge({ verdict, percent }: { verdict: "ai" | "human" | "mixed"; percent: number }) {
  const map = {
    ai: { label: "AI-Generated", bg: "bg-red-100 text-red-800 border-red-300", icon: <Brain className="w-4 h-4" /> },
    human: { label: "Human Written", bg: "bg-green-100 text-green-800 border-green-300", icon: <Sparkles className="w-4 h-4" /> },
    mixed: { label: "Mixed Content", bg: "bg-amber-100 text-amber-800 border-amber-300", icon: <AlertTriangle className="w-4 h-4" /> },
  }
  const { label, bg, icon } = map[verdict]
  return (
    <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-full border font-semibold text-sm ${bg}`}>
      {icon} {label} — {percent}% AI
    </div>
  )
}

// ─── Fixed Prop Interfaces ───────────────────────────────────────────────────
interface ClientPageProps {
  faqs: { q: string; a: string }[]
}

// ─── Main Component ───────────────────────────────────────────────────────────
export default function ClientPage({ faqs }: ClientPageProps) {
  const [text, setText] = useState("")
  const [result, setResult] = useState<ParsedResult | null>(null)
  const [rawResult, setRawResult] = useState("")
  const [error, setError] = useState("")
  const [copied, setCopied] = useState(false)
  const [copiedHuman, setCopiedHuman] = useState(false)
  const [humanizedText, setHumanizedText] = useState("")
  const [remainingTries, setRemainingTries] = useState(RATE_LIMIT_MAX)
  const [activeTab, setActiveTab] = useState<"analysis" | "charts" | "humanize">("analysis")
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  // Magic states
  const [magicState, setMagicState] = useState<"idle" | "detecting" | "humanizing">("idle")
  const [progress, setProgress] = useState(0)
  const [magicMessage, setMagicMessage] = useState("")

  const { copy } = useClipboard()
  const id = useId()
  const resultsRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    setRemainingTries(getRemainingTries())
  }, [])

  const freeModels = [
    "nvidia/nemotron-3-super-120b-a12b:free",
    "minimax/minimax-m2.5:free",
    "deepseek/deepseek-r1:free",
    "openai/gpt-oss-120b:free",
    "qwen/qwen3-next-80b-a3b-instruct:free",
    "meta-llama/llama-3.3-70b-instruct:free",
    "google/gemini-2.0-flash-lite-preview-02-05:free",
  ]

  const apiKeys = [
    process.env.NEXT_PUBLIC_OPENROUTER_API_KEY1,
    process.env.NEXT_PUBLIC_OPENROUTER_API_KEY2,
    process.env.NEXT_PUBLIC_OPENROUTER_API_KEY3,
    process.env.NEXT_PUBLIC_OPENROUTER_API_KEY4,
  ].filter(Boolean) as string[]

  const callOpenRouter = useCallback(
    async (systemPrompt: string, userContent: string): Promise<string> => {
      let lastError = ""
      for (const key of apiKeys) {
        for (const model of freeModels) {
          try {
            const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
              method: "POST",
              headers: {
                Authorization: `Bearer ${key}`,
                "Content-Type": "application/json",
                "HTTP-Referer": "https://thefreeaitools.com",
                "X-Title": "AI Text Detector",
              },
              body: JSON.stringify({
                model,
                messages: [
                  { role: "system", content: systemPrompt },
                  { role: "user", content: userContent },
                ],
              }),
            })
            if (response.ok) {
              const data = await response.json()
              return data.choices[0].message.content as string
            } else if (response.status === 401 || response.status === 402) {
              break
            }
          } catch (err: any) {
            lastError = err.message
          }
        }
      }
      throw new Error(lastError || "All API attempts failed.")
    },
    [apiKeys]
  )

  // ─── Magic Delay Execution ─────────────────────────────────────────────────
  const runWithMagicDelay = async (
    operation: "detecting" | "humanizing",
    apiCall: () => Promise<void>
  ) => {
    setMagicState(operation)
    setProgress(0)
    setMagicMessage("Initializing engine...")

    let isApiDone = false
    let apiError: any = null

    // Call API in background
    apiCall()
      .then(() => { isApiDone = true })
      .catch((e) => { isApiDone = true; apiError = e })

    const startTime = Date.now()
    const duration = 60000 // Force 60-second magic wait 

    return new Promise<void>((resolve) => {
      const timer = setInterval(() => {
        const elapsed = Date.now() - startTime
        const currentProgress = Math.min((elapsed / duration) * 100, 99)
        setProgress(currentProgress)

        // Dynamic 60s Engagement Messages
        if (elapsed < 10000) setMagicMessage("Verifying text length and fundamental structure...")
        else if (elapsed < 20000) setMagicMessage(operation === "detecting" ? "Scanning patterns against OpenAI ChatGPT signatures..." : "Removing predictable AI phrasing structures...")
        else if (elapsed < 30000) setMagicMessage(operation === "detecting" ? "Cross-referencing syntax using Claude AI models..." : "Applying human-like sentence variety using Claude AI...")
        else if (elapsed < 40000) setMagicMessage(operation === "detecting" ? "Calculating burstiness and multi-sentence variance..." : "Varying document burstiness and readability...")
        else if (elapsed < 50000) setMagicMessage(operation === "detecting" ? "Analyzing perplexity arrays using Gemini networks..." : "Enhancing perplexity to bypass traditional detectors...")
        else setMagicMessage("Finalizing results and compiling report...")

        if (elapsed >= duration) {
          if (isApiDone) {
            clearInterval(timer)
            setProgress(100)
            setMagicState("idle")
            if (apiError) {
              setError(apiError.message || "Operation failed.")
            }
            resolve()
          }
        }
      }, 500)
    })
  }

  const handleDetect = async () => {
    if (!text.trim()) { setError("Please enter some text to analyze."); return }
    if (apiKeys.length === 0) { setError("Configuration Error: No API keys found."); return }
    if (remainingTries <= 0) {
      setError(`Rate limit reached. You can run ${RATE_LIMIT_MAX} analyses per 3 hours. Resets in ${getResetMinutes()} min.`)
      return
    }

    setError("")
    setResult(null)
    setRawResult("")
    setHumanizedText("")

    await runWithMagicDelay("detecting", async () => {
      const raw = await callOpenRouter(
        `You are an expert AI content detection system. Analyze the given text and:
1. Provide a clear AI percentage (e.g. "85% AI-generated")
2. Assess perplexity level (low = predictable = AI)
3. Assess burstiness level (low = uniform = AI)
4. Note any repetitive patterns
5. Give a 2-3 sentence explanation of your verdict.
Be direct, accurate, and structured.`,
        text
      )
      incrementRateLimit()
      setRemainingTries(getRemainingTries())
      setRawResult(raw)
      setResult(parseResult(raw))
      setActiveTab("analysis")
    })

    setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100)
  }

  const handleHumanize = async () => {
    if (!text.trim()) { setError("Enter text to humanize."); return }
    if (apiKeys.length === 0) { setError("Configuration Error: No API keys found."); return }

    setError("")

    await runWithMagicDelay("humanizing", async () => {
      const humanized = await callOpenRouter(
        `You are an expert human writing editor. Rewrite the given text to:
- Sound naturally human-written, not AI-generated
- Vary sentence length and structure (mix short punchy and longer flowing sentences)
- Use contractions, occasional informal phrasing, and natural transitions
- Remove overly uniform or formal AI-like patterns
- Preserve the original meaning and key information entirely
- Do NOT add disclaimers. Output only the rewritten text.`,
        text
      )
      setHumanizedText(humanized)
      setActiveTab("humanize")
    })

    setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100)
  }

  const handleCopy = (content: string, setter: (v: boolean) => void) => {
    copy(content)
    setter(true)
    setTimeout(() => setter(false), 2000)
  }

  const stats = text ? getTextStats(text) : null

  // ─── Chart Data ──────────────────────────────────────────────────────────
  const doughnutData = result
    ? {
      labels: ["AI-Generated", "Human-Written"],
      datasets: [
        {
          data: [result.aiPercent, result.humanPercent],
          backgroundColor: ["#ef4444", "#22c55e"],
          borderColor: ["#dc2626", "#16a34a"],
          borderWidth: 2,
        },
      ],
    }
    : null

  const radarData = result
    ? {
      labels: ["Perplexity", "Burstiness", "Human Signals", "Repetition (inv)", "Naturalness"],
      datasets: [
        {
          label: "Text Profile",
          data: [
            result.perplexity,
            result.burstiness,
            result.humanPercent,
            100 - result.repetition,
            Math.round((result.perplexity + result.burstiness) / 2),
          ],
          backgroundColor: "rgba(99, 102, 241, 0.2)",
          borderColor: "#6366f1",
          borderWidth: 2,
          pointBackgroundColor: "#6366f1",
        },
      ],
    }
    : null

  const barData = result
    ? {
      labels: ["AI Score", "Perplexity", "Burstiness", "Repetition"],
      datasets: [
        {
          label: "Score (%)",
          data: [result.aiPercent, result.perplexity, result.burstiness, result.repetition],
          backgroundColor: ["#ef4444", "#f59e0b", "#3b82f6", "#8b5cf6"],
          borderRadius: 6,
        },
      ],
    }
    : null

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { position: "bottom" as const } },
  }

  const radarOptions = {
    responsive: true,
    maintainAspectRatio: false,
    scales: { r: { min: 0, max: 100, ticks: { stepSize: 20 } } },
    plugins: { legend: { position: "bottom" as const } },
  }

  // ─── Render ──────────────────────────────────────────────────────────────
  return (
    <>
      <ToolCard title="AI Text Detector">
        <div className="space-y-5">

          {/* Rate limit indicator */}
          <div className="flex items-center justify-between text-xs text-muted-foreground bg-muted/50 rounded-md px-3 py-2 border">
            <span className="flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5" />
              Free analyses remaining:
            </span>
            <span className={`font-semibold ${remainingTries === 0 ? "text-red-600" : remainingTries === 1 ? "text-amber-600" : "text-green-600"}`}>
              {remainingTries} / {RATE_LIMIT_MAX} (Resets 3 Hrs)
            </span>
          </div>

          {/* Input Phase UI */}
          {magicState === "idle" && (
            <div className="space-y-5 animate-in fade-in zoom-in-95 duration-300">
              {stats && (
                <div className="flex gap-4 text-xs text-muted-foreground">
                  <span className="flex items-center gap-1"><FileText className="w-3 h-3" /> {stats.words} words</span>
                  <span className="flex items-center gap-1"><BarChart2 className="w-3 h-3" /> {stats.sentences} sentences</span>
                  <span className="flex items-center gap-1"><Zap className="w-3 h-3" /> ~{stats.avgWordsPerSentence} words/sentence</span>
                </div>
              )}

              <div className="space-y-2">
                <Label htmlFor={`input-${id}`}>Paste Text to Analyze</Label>
                <Textarea
                  id={`input-${id}`}
                  placeholder="Paste any text here — essay, article, email, assignment — to detect AI authorship..."
                  value={text}
                  onChange={(e) => setText(e.target.value)}
                  className="min-h-[250px] resize-y"
                />
              </div>

              <div className="flex flex-col sm:flex-row gap-2">
                <Button
                  onClick={handleDetect}
                  disabled={!text.trim() || remainingTries <= 0}
                  className="flex-1 h-12"
                >
                  <Shield className="mr-2 h-5 w-5" /> Detect AI Content
                </Button>

                <Button
                  variant="outline"
                  onClick={handleHumanize}
                  disabled={!text.trim()}
                  className="flex-1 h-12"
                >
                  <Sparkles className="mr-2 h-5 w-5" /> Make It Human
                </Button>
              </div>

              {error && (
                <div className="p-3 text-sm text-red-800 bg-red-50 rounded-md border border-red-200 flex items-start gap-2">
                  <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" /> {error}
                </div>
              )}
            </div>
          )}

          {/* Magic Loading UI */}
          {magicState !== "idle" && (
            <div className="py-12 space-y-8 flex flex-col items-center justify-center text-center animate-in fade-in duration-500">
              <div className="relative flex items-center justify-center w-24 h-24">
                <div className="absolute inset-0 rounded-full border-4 border-primary/20 animate-ping"></div>
                <div className="absolute inset-2 rounded-full border-4 border-primary/40 animate-pulse"></div>
                <div className="bg-primary/10 p-4 rounded-full z-10">
                  {magicState === "detecting" ? (
                    <FileSearch className="w-10 h-10 text-primary animate-bounce" />
                  ) : (
                    <Wand2 className="w-10 h-10 text-primary animate-bounce" />
                  )}
                </div>
              </div>

              <div className="space-y-3 w-full max-w-md">
                <h3 className="text-lg font-semibold tracking-tight">{magicMessage}</h3>
                <div className="h-3 w-full bg-muted rounded-full overflow-hidden">
                  <div
                    className="h-full bg-primary transition-all ease-linear duration-500 rounded-full relative"
                    style={{ width: `${progress}%` }}
                  >
                    <div className="absolute inset-0 bg-white/20 w-full animate-[shimmer_2s_infinite]"></div>
                  </div>
                </div>
                <p className="text-xs text-muted-foreground font-medium animate-pulse">
                  {magicState === "detecting"
                    ? "Applying advanced multi-model AI detection. Please do not close this window..."
                    : "Rewriting patterns to sound natively human. Please do not close this window..."}
                </p>
              </div>
            </div>
          )}

          {/* Results Area */}
          {magicState === "idle" && (result || humanizedText) && (
            <div ref={resultsRef} className="mt-2 space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">

              <div className="flex border-b">
                {result && (
                  <>
                    <button
                      onClick={() => setActiveTab("analysis")}
                      className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${activeTab === "analysis" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}
                    >
                      Analysis
                    </button>
                    <button
                      onClick={() => setActiveTab("charts")}
                      className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${activeTab === "charts" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}
                    >
                      Charts
                    </button>
                  </>
                )}
                {humanizedText && (
                  <button
                    onClick={() => setActiveTab("humanize")}
                    className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${activeTab === "humanize" ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}
                  >
                    Humanized Text
                  </button>
                )}
              </div>

              {activeTab === "analysis" && result && (
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <VerdictBadge verdict={result.verdict} percent={result.aiPercent} />
                    <Button variant="ghost" size="sm" onClick={() => handleCopy(rawResult, setCopied)}>
                      {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                    </Button>
                  </div>

                  <div className="space-y-3">
                    {[
                      { label: "AI Probability", value: result.aiPercent, color: "bg-red-500" },
                      { label: "Human Writing Signals", value: result.humanPercent, color: "bg-green-500" },
                      { label: "Perplexity (higher = more human)", value: result.perplexity, color: "bg-blue-500" },
                      { label: "Burstiness (higher = more human)", value: result.burstiness, color: "bg-indigo-500" },
                      { label: "Repetition Detected", value: result.repetition, color: "bg-purple-500" },
                    ].map(({ label, value, color }) => (
                      <div key={label} className="space-y-1">
                        <div className="flex justify-between text-xs text-muted-foreground">
                          <span>{label}</span>
                          <span className="font-medium">{value}%</span>
                        </div>
                        <div className="h-2 rounded-full bg-muted overflow-hidden">
                          <div
                            className={`h-full rounded-full transition-all duration-700 ease-out ${color}`}
                            style={{ width: `${value}%` }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="p-4 bg-muted rounded-md border text-sm whitespace-pre-wrap leading-relaxed shadow-inner max-h-[400px] overflow-y-auto">
                    {rawResult}
                  </div>
                </div>
              )}

              {activeTab === "charts" && result && (
                <div className="space-y-6">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <p className="text-sm font-medium text-center">AI vs Human Split</p>
                      <div className="h-52">
                        {doughnutData && <Doughnut data={doughnutData} options={chartOptions} />}
                      </div>
                    </div>
                    <div className="space-y-2">
                      <p className="text-sm font-medium text-center">Score Breakdown</p>
                      <div className="h-52">
                        {barData && <Bar data={barData} options={chartOptions} />}
                      </div>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <p className="text-sm font-medium text-center">Writing Profile Radar</p>
                    <div className="h-64">
                      {radarData && <Radar data={radarData} options={radarOptions} />}
                    </div>
                  </div>
                </div>
              )}

              {activeTab === "humanize" && humanizedText && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label>Humanized Version</Label>
                    <div className="flex gap-2">
                      <Button variant="ghost" size="sm" onClick={() => handleCopy(humanizedText, setCopiedHuman)}>
                        {copiedHuman ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => { setText(humanizedText); setHumanizedText(""); setResult(null); setActiveTab("analysis") }}>
                        <RefreshCw className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                  <div className="p-5 bg-green-50 border border-green-200 rounded-md text-sm whitespace-pre-wrap leading-relaxed shadow-inner max-h-[400px] overflow-y-auto">
                    {humanizedText}
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Tip: Click the ↺ icon to load this text back into the detector and re-analyze it.
                  </p>
                </div>
              )}
            </div>
          )}
        </div>
      </ToolCard>

      {/* ─── Rest of layout (How it works, FAQ, Use cases) stays the same ─── */}
      <section className="mt-10 space-y-4" aria-labelledby="how-it-works">
        <h2 id="how-it-works" className="text-xl font-bold">How the AI Text Detector Works</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {[
            { icon: <FileText className="w-5 h-5 text-primary" />, title: "1. Paste Your Text", desc: "Submit any text — essays, emails, blog posts, academic papers, product descriptions, or social content." },
            { icon: <Brain className="w-5 h-5 text-primary" />, title: "2. Multi-Model Analysis", desc: "Our system sends the text through multiple frontier LLMs and cross-validates AI probability, perplexity, and burstiness scores." },
            { icon: <BarChart2 className="w-5 h-5 text-primary" />, title: "3. Visual Results", desc: "Get an AI percentage score, interactive charts, and a detailed explanation — instantly and for free." },
          ].map(({ icon, title, desc }) => (
            <div key={title} className="p-4 border rounded-lg space-y-2 bg-muted/30">
              {icon}
              <h3 className="font-semibold text-sm">{title}</h3>
              <p className="text-sm text-muted-foreground">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 space-y-3" aria-labelledby="use-cases">
        <h2 id="use-cases" className="text-xl font-bold">Who Uses an AI Content Detector?</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {[
            { title: "Teachers & Professors", desc: "Verify student essays and academic submissions for AI-generated content." },
            { title: "Editors & Publishers", desc: "Ensure submitted articles meet human authorship standards before publishing." },
            { title: "SEO & Content Teams", desc: "Check if content will be flagged by Google's AI content policies before publishing." },
            { title: "Hiring Managers", desc: "Detect AI-written cover letters and job application essays." },
            { title: "Students", desc: "Test your own writing to ensure it won't be flagged by your institution's detector." },
            { title: "Researchers", desc: "Study the linguistic patterns that separate AI from human text at scale." },
          ].map(({ title, desc }) => (
            <div key={title} className="p-3 border rounded-md bg-muted/20 space-y-1">
              <p className="font-medium text-sm">{title}</p>
              <p className="text-xs text-muted-foreground">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 space-y-3" aria-labelledby="faq-heading">
        <h2 id="faq-heading" className="text-xl font-bold">Frequently Asked Questions</h2>
        <div className="divide-y border rounded-lg overflow-hidden bg-card">
          {faqs.map((item, i) => (
            <div key={i}>
              <button
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full flex items-center justify-between p-4 text-left text-sm font-medium hover:bg-muted/50 transition-colors"
                aria-expanded={openFaq === i}
              >
                {item.q}
                {openFaq === i ? <ChevronUp className="w-4 h-4 shrink-0" /> : <ChevronDown className="w-4 h-4 shrink-0" />}
              </button>
              {openFaq === i && (
                <div className="px-4 pb-4 text-sm text-muted-foreground leading-relaxed">{item.a}</div>
              )}
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 space-y-2" aria-labelledby="related-tools">
        <h2 id="related-tools" className="text-xl font-bold">Related: Detect AI Text by Platform</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Our AI text detector works perfectly to detect content generated using AI, including models like <strong>ChatGPT</strong>, <strong>using Claude AI</strong>,{" "}
          <strong>Gemini</strong>, <strong>Copilot</strong>, <strong>Llama</strong>, <strong>Mistral</strong>,
          and other large language models. Use it to check if an essay was written using ChatGPT, verify articles, detect emails written by AI,
          review social media captions, marketing copy, and more.
        </p>
      </section>
    </>
  )
}