const base=(process.argv[2]||'http://127.0.0.1:3000').replace(/\/$/,'');
const pages=['/','/live-tv','/sports','/movies','/series','/pricing','/order','/setup-guides','/world-cup-2026','/world-cup-2026/final','/world-cup-2026/final-standings','/world-cup-2026/awards','/world-cup-history','/world-cup-history/winners','/world-cup-history/records','/world-cup-2026/replays','/world-cup-2026/replays/usa','/world-cup-2026/teams','/world-cup-2026/host-cities','/guides','/guides/is-iptv-legal','/guides/watch-soccer-without-cable','/guides/streaming-latency','/guides/sports-streaming-accessibility','/data','/research','/research/streaming-benchmark-methodology','/research/world-cup-2026-replay-source-tracker','/updates','/guides/internet-speed-4k-sports','/guides/stop-sports-buffering','/guides/best-device-live-sports','/guides/4k-hdr-sports-setup','/about','/editorial-policy','/corrections','/contact','/support','/privacy-policy','/terms-of-service'];
let fails=0;const fail=x=>{fails++;console.error('  ✗ '+x)},pass=x=>console.log('  ✓ '+x);
for(const path of pages){const r=await fetch(base+path,{redirect:'manual'});const h=await r.text();console.log('\n'+path);r.status===200?pass('HTTP 200'):fail('HTTP '+r.status);const title=h.match(/<title>(.*?)<\/title>/s)?.[1]||'';const desc=h.match(/<meta name="description" content="([^"]+)/)?.[1]||'';const can=h.match(/<link rel="canonical" href="([^"]+)/)?.[1]||'';const og=h.match(/<meta property="og:image" content="([^"]+)/)?.[1]||'';const twitter=h.match(/<meta name="twitter:image" content="([^"]+)/)?.[1]||'';const h1=(h.match(/<h1[\s>]/g)||[]).length;title.length>=20&&title.length<=90?pass('Title '+title.length):fail('Title '+title.length);desc.length>=70&&desc.length<=180?pass('Description '+desc.length):fail('Description '+desc.length);can.startsWith('https://')?pass('Absolute canonical'):fail('Canonical');og.startsWith('https://watchworldcup.us/images/og/')&&twitter===og?pass('Unique social image metadata'):fail('Social image metadata');h1===1?pass('One H1'):fail('H1 count '+h1);/content="index, follow"/i.test(h.match(/<meta name="robots"[^>]*>/)?.[0]||'')?pass('Explicit index, follow'):fail('Indexing directive mismatch')}
for(const p of ['/not-a-real-page','/blog/definitely-removed-iptv-offer']){const r=await fetch(base+p,{redirect:'manual'});r.status===404?pass(p+' returns 404'):fail(p+' returns '+r.status)}
const legacy=await fetch(base+'/world-cup-2026-iptv/matches/mexico-vs-south-africa/',{redirect:'manual'});[307,308].includes(legacy.status)?pass('Legacy match redirect'):fail('Legacy redirect '+legacy.status);
const checkout=await fetch(base+'/checkout',{redirect:'manual'});checkout.status===410?pass('Legacy checkout 410'):fail('Checkout '+checkout.status);
const robots=await(await fetch(base+'/robots.txt')).text();/Sitemap: https:\/\//.test(robots)?pass('Robots sitemap'):fail('Robots sitemap');for(const path of ['/checkout','/cart','/client-area'])robots.includes(`Disallow: ${path}`)?pass(`Robots blocks ${path}`):fail(`Robots does not block ${path}`);
const map=await(await fetch(base+'/sitemap.xml')).text();/<priority>|<changefreq>/.test(map)?fail('Ignored sitemap tags'):pass('Clean sitemap');map.includes('/research/world-cup-2026-replay-source-tracker')?pass('Tracker in sitemap'):fail('Tracker absent from sitemap');(map.match(/<image:image>/g)||[]).length===pages.length?pass(`${pages.length} sitemap image entries`):fail('Sitemap image entry count');
const pricing=await(await fetch(base+'/pricing')).text();['$25','$38','$62'].every(price=>pricing.includes(price))?pass('Pricing renders all three listed prices'):fail('Pricing values missing');!pricing.includes('"@type":"Product"')&&!pricing.includes('"@type":"Offer"')?pass('Pricing avoids unsupported Product/Offer schema'):fail('Unsupported pricing schema');pricing.includes('api.whatsapp.com')?pass('Pricing exposes WhatsApp order flow'):fail('Pricing WhatsApp CTA missing');
const orderPage=await(await fetch(base+'/order')).text();orderPage.includes('Private-by-design order preparation')&&orderPage.includes('Continue order on WhatsApp')?pass('Order page exposes private-by-design WhatsApp workflow'):fail('Order workflow missing');!orderPage.includes('"@type":"Product"')&&!orderPage.includes('"@type":"Offer"')?pass('Order page avoids unsupported Product/Offer schema'):fail('Unsupported order schema');
const tracker=await(await fetch(base+'/research/world-cup-2026-replay-source-tracker')).text();tracker.includes('"@type":"Dataset"')&&tracker.includes('/downloads/world-cup-2026-replay-sources.csv')&&tracker.includes('/downloads/world-cup-2026-replay-sources.json')?pass('Visible tracker has Dataset and CSV references'):fail('Tracker Dataset or CSV reference missing');
const csv=await fetch(base+'/downloads/world-cup-2026-replay-sources.csv');csv.status===200&&/text\/csv/i.test(csv.headers.get('content-type')||'')?pass('Replay-source CSV served as text/csv'):fail(`Replay-source CSV ${csv.status} ${csv.headers.get('content-type')}`);
const standings=await(await fetch(base+'/world-cup-2026/final-standings')).text();standings.includes('"@type":"Dataset"')&&standings.includes('/downloads/world-cup-2026-final-standings.csv')&&standings.includes('/downloads/world-cup-2026-final-standings.json')?pass('Final standings has Dataset and CSV references'):fail('Final standings Dataset or CSV reference missing');const standingRows=((standings.match(/<tbody>[\s\S]*?<\/tbody>/)||[''])[0].match(/<tr/g)||[]).length;standingRows===48?pass('Final standings renders 48 rows'):fail(`Final standings renders ${standingRows} rows`);
const standingsCsv=await fetch(base+'/downloads/world-cup-2026-final-standings.csv');const standingsCsvBody=await standingsCsv.text();standingsCsv.status===200&&/text\/csv/i.test(standingsCsv.headers.get('content-type')||'')?pass('Final-standings CSV served as text/csv'):fail(`Final-standings CSV ${standingsCsv.status} ${standingsCsv.headers.get('content-type')}`);standingsCsvBody.trim().split(/\r?\n/).length===49?pass('Final-standings CSV has header plus 48 rows'):fail('Final-standings CSV row count mismatch');
const winners=await(await fetch(base+'/world-cup-history/winners')).text();winners.includes('"@type":"Dataset"')&&winners.includes('/downloads/world-cup-winners-1930-2026.csv')&&winners.includes('/downloads/world-cup-winners-1930-2026.json')?pass('Winners archive has Dataset and CSV references'):fail('Winners Dataset or CSV reference missing');const winnerRows=((winners.match(/<tbody>[\s\S]*?<\/tbody>/)||[''])[0].match(/<tr/g)||[]).length;winnerRows===23?pass('Winners archive renders 23 editions'):fail(`Winners archive renders ${winnerRows} editions`);
const winnersCsv=await fetch(base+'/downloads/world-cup-winners-1930-2026.csv');const winnersCsvBody=await winnersCsv.text();winnersCsv.status===200&&/text\/csv/i.test(winnersCsv.headers.get('content-type')||'')?pass('Winners CSV served as text/csv'):fail(`Winners CSV ${winnersCsv.status}`);winnersCsvBody.trim().split(/\r?\n/).length===24?pass('Winners CSV has header plus 23 rows'):fail('Winners CSV row count mismatch');
const recordsPage=await(await fetch(base+'/world-cup-history/records')).text();recordsPage.includes('"@type":"Dataset"')&&recordsPage.includes('/downloads/world-cup-title-records.csv')&&recordsPage.includes('/downloads/world-cup-title-records.json')?pass('World Cup records has Dataset and CSV/JSON references'):fail('World Cup records Dataset mismatch');const recordRows=((recordsPage.match(/<tbody>[\s\S]*?<\/tbody>/)||[''])[0].match(/<tr/g)||[]).length;recordRows===13?pass('World Cup records renders 13 finalist teams'):fail(`World Cup records renders ${recordRows} teams`);
const recordsCsv=await fetch(base+'/downloads/world-cup-title-records.csv');const recordsCsvBody=await recordsCsv.text();recordsCsv.status===200&&/text\/csv/i.test(recordsCsv.headers.get('content-type')||'')?pass('World Cup records CSV served as text/csv'):fail(`World Cup records CSV ${recordsCsv.status}`);recordsCsvBody.trim().split(/\r?\n/).length===14?pass('World Cup records CSV has header plus 13 rows'):fail('World Cup records CSV row count mismatch');
const dataPage=await(await fetch(base+'/data')).text();dataPage.includes('"@type":"DataCatalog"')&&(dataPage.match(/"@type":"Dataset"/g)||[]).length===4?pass('Open data page has DataCatalog and four Dataset references'):fail('DataCatalog schema mismatch');dataPage.includes('/downloads/data-checksums.sha256')?pass('Open data page exposes checksums'):fail('Checksum manifest link missing');
const finalPage=await(await fetch(base+'/world-cup-2026/final')).text();finalPage.includes('"@type":"SportsEvent"')&&finalPage.includes('EventCompleted')?pass('Final has completed SportsEvent schema'):fail('Final SportsEvent schema missing or stale');
const feed=await(await fetch(base+'/feed.xml')).text();feed.includes('/research/world-cup-2026-replay-source-tracker')?pass('Tracker in RSS feed'):fail('Tracker absent from RSS feed');for(const path of ['/pricing','/order','/live-tv','/sports','/movies','/series','/setup-guides','/world-cup-2026/final','/world-cup-2026/final-standings','/world-cup-2026/awards','/world-cup-history','/world-cup-history/winners','/world-cup-history/records','/data'])feed.includes(path)?pass(`${path} in RSS feed`):fail(`${path} absent from RSS feed`);
if(fails){console.error(`\n${fails} SEO check failure(s)`);process.exit(1)}console.log('\nSEO check passed')
