import { ArrowRightIcon } from '../../_components/Icons';
import Link from 'next/link';
import PageShell from '../../_components/PageShell';
import SourceList from '../../_components/SourceList';
import { BreadcrumbSchema } from '../../schema';
import { pageMetadata } from '@/lib/seo';
import { officialSources } from '@/lib/site';
const path='/world-cup-2026/teams';
export const metadata=pageMetadata({title:'World Cup 2026 Teams — All 48 Nations | WATCHWORLDCUP',description:'Browse all 48 teams in the expanded World Cup 2026 tournament, organized across twelve groups of four. Includes group stage results and knockout progression for each nation.',path});
const groups={A:['Mexico','Czechia','South Africa','South Korea'],B:['Canada','Bosnia and Herzegovina','Qatar','Switzerland'],C:['Brazil','Haiti','Morocco','Scotland'],D:['Australia','Paraguay','Türkiye','United States'],E:['Curaçao','Ecuador','Germany','Côte d’Ivoire'],F:['Japan','Netherlands','Sweden','Tunisia'],G:['Belgium','Egypt','Iran','New Zealand'],H:['Cabo Verde','Saudi Arabia','Spain','Uruguay'],I:['France','Iraq','Norway','Senegal'],J:['Argentina','Algeria','Austria','Jordan'],K:['Colombia','DR Congo','Portugal','Uzbekistan'],L:['Croatia','England','Ghana','Panama']};
export default function Page(){return <><BreadcrumbSchema items={[{name:'Home',path:'/'},{name:'World Cup 2026',path:'/world-cup-2026'},{name:'Teams',path}]}/><PageShell eyebrow="Tournament field" title="All 48 World Cup 2026 teams, organized by group." description="The 2026 tournament expanded to twelve groups of four teams. This page preserves the field without generating thin, near-identical team sales pages." breadcrumbs={[{label:'Home',href:'/'},{label:'2026 Archive',href:'/world-cup-2026'},{label:'Teams'}]}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(groups).map(([g,teams])=><section key={g} className="glass rounded-2xl p-6"><p className="eyebrow">Group {g}</p><ul className="mt-5 space-y-3">{teams.map(t=><li key={t} className="flex items-center justify-between border-b border-white/5 pb-3 text-sm font-bold last:border-0 last:pb-0"><span>{t}</span><span className="h-2 w-2 rounded-full bg-red-400/70"/></li>)}</ul></section>)}</div><div className="mt-12 rounded-2xl border border-white/10 bg-white/[.035] p-7"><h2 className="text-2xl font-black">Why there are no 48 thin team pages</h2><p className="mt-4 max-w-4xl text-sm leading-7 text-slate-400">A team URL should exist only when it adds a complete tournament record, verified results, official replay links, sources, and unique analysis. Replacing names inside the same sales template does not help readers and is not part of this rebuild.</p><Link href="/world-cup-2026/final-standings" className="mt-5 inline-block font-black text-red-400">See how all 48 teams finished<ArrowRightIcon className="ml-2 inline h-4 w-4"/></Link></div><SourceList sources={[{name:'FIFA World Cup 2026 tournament hub',url:officialSources.fifaTournament}]}/></PageShell></>}
